#!/usr/bin/env python
# encoding: utf-8

name = "PlasmaArgonDimer"
shortDesc = u"Argon dimer-ion formation, dissociative recombination, and electron-impact dissociation"
longDesc = u"""
The three shipped Ar2+ kinetics entries are isolated from PlasmaArgon so ordinary
argon decks do not load dimer chemistry. Tg dependence above 298.15 K is UNSOURCED
Tg DEPENDENCE: the conversion is an extrapolated law and the DR and DEI entries use
their 300 K forms. At 1000 K about 65% of Ar2+ is vibrationally excited, which Shiu &
Biondi expect to recombine more slowly. The library excludes the Mehr & Biondi law,
the ground-product DR arm, and any extrapolation override.
"""

entry(
    index = 0,
    label = "Arp + Ar + Ar <=> Ar2p + Ar",
    reversible = True,
    kinetics = Arrhenius(A=(2.25e-31, 'cm^6/(molecule^2*s)'), n=-0.4,
                         Ea=(0, 'J/mol'), T0=(300, 'K'),
                         Tmin=(150, 'K'), Tmax=(300, 'K')),
    shortDesc = u"Jones, Lister, Wareing & Twiddy (1980), 150–300 K; extrapolated above 300 K",
    longDesc = u"""
Three-body conversion: kf = 2.25e-31 (Tg/300 K)^-0.4 cm^6/(molecule^2*s).

SOURCE. Jones, Lister, Wareing & Twiddy, J. Phys. B 13 (1980), graded secondary
(Petrov & Ferreira, arXiv:1308.2593, Table 4); also Kemaneci et al. (2017), Table
III row 30. The measured 295–320 K spread is reported by Johnsen, Chen & Biondi,
J. Chem. Phys. 73 (1980), p. 1719, Table III (primary-read). Source validity is
150–300 K and is not widened; the law is extrapolated above 300 K. The reverse is
generated by detailed balance with PlasmaThermo [Ar2p]. The SI/molar conversion and
reverse coefficient are derived.

UNSOURCED Tg DEPENDENCE. The law is sourced to 300 K; above 300 K this is the extrapolated
law. At 1000 K about 65% of Ar2+ is vibrationally excited, which Shiu & Biondi expect to
recombine more slowly. The PlasmaThermo data for Arp and Ar2p both begin at 298.15 K, so the
detailed-balance reverse below 298.15 K -- inside the declared 150-300 K source range for the
forward law -- rests on extrapolated thermochemistry; decks run at >= 298.15 K.
""",
)

entry(
    index = 1,
    label = "Ar2p + e- => Ars + Ar",
    reversible = False,
    kinetics = TwoTemperaturePlasma(A=(9.1e-7, 'cm^3/(molecule*s)'), n=-0.61,
                                    T0=(300, 'K'), Ea_g=(0, 'eV/molecule'),
                                    Ea_e=(0, 'eV/molecule'), Tmin=(300, 'K'),
                                    Tmax=(8500, 'K')),
    shortDesc = u"Shiu & Biondi (1978) central DR law, 300–8500 K; explicit e-; metastable-product upper-bound convention",
    longDesc = u"""
EXTRAPOLATED DISSOCIATIVE-RECOMBINATION RATE above 8500 K.
The central law is alpha_SB(Te) = 9.1e-7 (300 K/Te)^0.61 cm^3/s, valid for
300–8500 K with ±10% experimental uncertainty inside that range only.

SOURCE. Shiu & Biondi, Phys. Rev. A 17, 868 (1978), DOI 10.1103/PhysRevA.17.868,
Eq. (3), p. 868, and Table I/Fig. 2 (primary-read). The coefficient, exponent, range,
and uncertainty are sourced; m^3/(mol*s) values are derived. The product convention
is the upper-bound metastable-source convention, not a measured branching: never cite
0.356/0.644 as fractions. A mutually exclusive deck-local Ar + Ar arm is not shipped.

Ar2+ dissociative recombination uses Shiu and Biondi (1978) as the central rate law.
The source fit is stated for 300–8500 K, whereas present 10,400–13,500 K evaluations
are extrapolations. Mehr and Biondi (1968) is a correlated historical sensitivity,
not this library entry. The published +/-10% uncertainty is not extended beyond the
measured temperature range.

The electron-energy equation removes 3/2 k_B Te per recombined electron, labelled
BULK-MEAN ELECTRON-ENERGY APPROXIMATION. This is not the reaction-weighted mean energy:
with the stored signed exponent n = -0.61 (alpha proportional to Te^n), the Maxwellian
reaction-weighted value is (3/2 + n) k_B Te = 0.89 k_B Te; never use |n|. The bulk-mean
approximation is retained for this build and is not exact.

UNSOURCED Tg DEPENDENCE. Above 298.15 K this entry uses its 300 K form. At 1000 K about
65% of Ar2+ is vibrationally excited, which Shiu & Biondi expect to recombine more slowly.
EXTRAPOLATED DISSOCIATIVE-RECOMBINATION RATE applies whenever Te is above 8500 K.
""",
)

entry(
    index = 2,
    label = "Ar2p + e- => Arp + Ar + e-",
    reversible = False,
    kinetics = TwoTemperaturePlasma(A=(1.11e-12, 'm^3/(molecule*s)'), n=0,
                                    Ea_g=(2.94092, 'eV/molecule'),
                                    Ea_e=(2.94092, 'eV/molecule'),
                                    Tmin=(298.15, 'K'), Tmax=(298.15, 'K')),
    shortDesc = u"Kemaneci et al. (2017), Table III row 29, 298.15 K form",
    longDesc = u"""
Electron-impact dissociation (DEI), stored in its 298.15 K form:
TwoTemperaturePlasma(A=1.11e-12 m^3/(molecule*s), n=0,
Ea_g=Ea_e=2.94092 eV/molecule). SOURCE. Kemaneci et al., J. Phys. D (2017),
DOI 10.1088/1361-6463/aa7093, Table III row 29 (full-text/arXiv grade; source chain
to Kabouzi et al. 2007 is secondary). Tmin = Tmax = 298.15 K. The stored coefficient
and activation energy are sourced; the cancellation to the 298.15 K form is derived.

UNSOURCED Tg DEPENDENCE. Above 298.15 K this entry uses its 300 K form. At 1000 K about
65% of Ar2+ is vibrationally excited, which Shiu & Biondi expect to recombine more slowly.
""",
)
