#!/usr/bin/env python
# encoding: utf-8

name = "Disproportionation/groups"
shortDesc = ""
longDesc = """
If a birad, reaction site *1 needs to be a triplet.
If a birad, reaction site *3 needs to be a triplet.
If a tri-rad or quad-rad, reaction site *1 and *3 can be anything but singlet.
"""

template(reactants=["Root"], products=["Y_H", "X_R"], ownReverse=False)

reverse = "Molecular_Addition"
reversible = True

reactantNum = 2

productNum = 2

autoGenerated = True

recipe(actions=[
    ['FORM_BOND', '*1', 1, '*4'],
    ['BREAK_BOND', '*2', 1, '*4'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['LOSE_RADICAL', '*1', '1'],
    ['LOSE_RADICAL', '*3', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 R!H u0         {2,[S,D,B]} {3,S}
2 *3 R!H u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 R   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]}
2 *3 R!H u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 R   u[1,2,3,4]
5    R!H ux         {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_Ext-1R!H-R_4R->O",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4]
5    C ux         {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_Ext-1R!H-R_4R->O_Ext-4O-R",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4] {6,[S,D,T,B]}
5    C ux         {1,[S,D,T,B]}
6    O ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_Ext-1R!H-R_4R->O_Ext-4O-R_Sp-5R!H-1R!H",
    group = 
"""
1 *2 C u0     {2,S} {3,S} {5,S}
2 *3 C u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 O u1     {6,[S,D,T,B]}
5    C ux     {1,S}
6    O ux     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_Ext-1R!H-R_4R->O_Ext-4O-R_Sp-5R!H-1R!H_Ext-5R!H-R",
    group = 
"""
1 *2 C u0     {2,S} {3,S} {5,S}
2 *3 C u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 O u1     {6,[S,D,T,B]}
5    C ux     {1,S} {7,[S,D,T,B]}
6    O ux     {4,[S,D,T,B]}
7    C ux     {5,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_Ext-1R!H-R_4R->O_Ext-4O-R_Sp-5R!H-1R!H_Ext-5R!H-R_Ext-1R!H-R",
    group = 
"""
1 *2 C u0     {2,S} {3,S} {5,S} {8,S}
2 *3 C u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 O u1     {6,[S,D,T,B]}
5    C ux     {1,S} {7,[S,D,T,B]}
6    O ux     {4,[S,D,T,B]}
7    C ux     {5,[S,D,T,B]}
8    C u0     {1,S}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_Ext-1R!H-R_4R->O_Ext-4O-R_Sp-5R!H-1R!H_Ext-5R!H-R_Ext-1R!H-R_Ext-8R!H-R",
    group = 
"""
1 *2 C   u0     r0 {2,S} {3,S} {5,S} {8,S}
2 *3 C   u[1,2] r0 {1,S}
3 *4 H   u0     r0 {1,S}
4 *1 O   u1     r0 {6,[S,D,T,B]}
5    C   ux     r0 {1,S} {7,[S,D,T,B]}
6    O   ux     {4,[S,D,T,B]}
7    C   ux     {5,[S,D,T,B]}
8    C   u0     r0 {1,S} {9,[S,D,T,B]}
9    R!H ux     {8,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_Ext-1R!H-R_4R->O_Ext-4O-R_Sp-5R!H-1R!H_Ext-1R!H-R",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,S} {5,S} {7,S}
2 *3 C u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 r0 {6,S}
5    C u0 r0 {1,S}
6    O u1 r0 {4,S}
7    C u0 r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_Ext-1R!H-R_4R->O_Ext-4O-R_N-Sp-5R!H-1R!H",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {5,D}
2 *3 C u1         {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4] {6,S}
5    C u0         {1,D}
6    O u1         r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_Ext-1R!H-R_4R->O_Sp-5R!H-1R!H",
    group = 
"""
1 *2 C u0 {2,S} {3,S} {5,S}
2 *3 C u1 {1,S}
3 *4 H u0 {1,S}
4 *1 O u1
5    C u0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_Ext-1R!H-R_4R->O_Sp-5R!H-1R!H_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S} {5,S} {6,[S,D,T,B]}
2 *3 C   u1 r0 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 O   u1 r0
5    C   u0 r0 {1,S}
6    R!H ux {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_Ext-1R!H-R_4R->O_N-Sp-5R!H-1R!H",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {5,D}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 O u[1,2,3,4]
5    C ux         {1,D}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_Ext-1R!H-R_N-4R->O",
    group = 
"""
1 *2 C         u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]}
2 *3 R!H       u[1,2]     {1,[S,D,B]}
3 *4 H         u0         {1,S}
4 *1 [H,C,N,S] u[1,2,3,4]
5    R!H       ux         {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R",
    group = 
"""
1 *2 C         u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C         u[1,2]     {1,[S,D,B]}
3 *4 H         u0         {1,S}
4 *1 [H,C,N,S] u[1,2,3,4]
5    R!H       ux         {1,[S,D,T,B]}
6    R!H       ux         {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4]
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {7,[S,D,T,B]}
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
7    R!H ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_Sp-7R!H#4C",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u1 r0 {1,S}
3 *4 H   u0 {1,S}
4 *1 C   u1 r0 {7,T}
5    R!H ux {1,[S,D,T,B]}
6    R!H ux {1,[S,D,T,B]}
7    R!H u0 r0 {4,T}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {7,[S,D,B]}
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
7    R!H ux         {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {7,[S,D,B]}
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
7    C   ux         {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_Ext-4C-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {7,S} {8,[S,D,T,B]}
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
7    C   ux         {4,S}
8    R!H ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_Ext-4C-R_Ext-4C-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         r0 {1,S}
4 *1 C   u[1,2,3,4] {7,S} {8,[S,D,T,B]} {9,[S,D,T,B]}
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
7    C   ux         {4,S}
8    R!H ux         {4,[S,D,T,B]}
9    R!H ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_Ext-7C-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {7,[S,D,B]}
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
7    C   ux         {4,[S,D,B]} {8,[S,D,T,B]}
8    R!H ux         {7,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_Sp-7C-4C",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {7,S}
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
7    C   ux         {4,S}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_N-Sp-7C-4C",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {7,D}
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
7    C   ux         {4,D}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_N-7R!H->C",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         r0 {1,S}
4 *1 C   u[1,2,3,4] {7,[S,D,B]}
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
7    O   ux         {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_N-4CHNS->C",
    group = 
"""
1 *2 C     u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C     u[1,2]     {1,[S,D,B]}
3 *4 H     u0         {1,S}
4 *1 [H,S] u[1,2,3,4]
5    R!H   ux         {1,[S,D,T,B]}
6    R!H   ux         {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_N-4CHNS->C_4HS->H",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         r0 {1,S}
4 *1 H   u[1,2,3,4]
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 28,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_N-4CHNS->C_N-4HS->H",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 S   u[1,2,3,4]
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 29,
    label = "Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_N-4CHNS->C_N-4HS->H_Ext-4S-R_Ext-7R!H-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B]} {6,[S,D,T,B]}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         r0 {1,S}
4 *1 S   u[1,2,3,4] {7,S}
5    R!H ux         {1,[S,D,T,B]}
6    R!H ux         {1,[S,D,T,B]}
7    C   u0         r0 {4,S} {8,[S,D,T,B]}
8    R!H ux         {7,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 30,
    label = "Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {5,D}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4]
5    C ux         {1,D}
""",
    kinetics = None,
)

entry(
    index = 31,
    label = "Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,D}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {6,[S,D,T,B]}
5    C   ux         {1,D}
6    R!H ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 32,
    label = "Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Ext-6R!H-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,D}
2 *3 C   u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {6,[S,D,T,B]}
5    C   ux         {1,D}
6    C   u0         r0 {4,[S,D,T,B]} {7,[S,D,T,B]}
7    R!H ux         {6,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 33,
    label = "Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Ext-4CHNS-R",
    group = 
"""
1 *2 C   u0 {2,S} {3,S} {5,D}
2 *3 C   u1 {1,S}
3 *4 H   u0 {1,S}
4 *1 C   u1 {6,[S,D,T,B]} {7,[S,D,T,B]}
5    C   u0 {1,D}
6    R!H ux {4,[S,D,T,B]}
7    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 34,
    label = "Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Ext-4CHNS-R_Ext-4CHNS-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S} {5,D}
2 *3 C   u1 r0 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 C   u1 r0 {6,[S,D,T,B]} {7,[S,D,T,B]} {8,[S,D,T,B]}
5    C   u0 r0 {1,D}
6    R!H ux {4,[S,D,T,B]}
7    R!H ux {4,[S,D,T,B]}
8    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 35,
    label = "Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Sp-6R!H-4CHNS",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {5,D}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] {6,S}
5    C ux         {1,D}
6    C ux         {4,S}
""",
    kinetics = None,
)

entry(
    index = 36,
    label = "Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_N-Sp-6R!H-4CHNS",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {5,D}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] {6,D}
5    C ux         {1,D}
6    C ux         {4,D}
""",
    kinetics = None,
)

entry(
    index = 37,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H",
    group = 
"""
1 *2 C         u0         {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H       u[1,2]     {1,[S,D,B]}
3 *4 H         u0         {1,S}
4 *1 [H,C,N,S] u[1,2,3,4]
5    C         ux         {1,[S,B]}
""",
    kinetics = None,
)

entry(
    index = 38,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R",
    group = 
"""
1 *2 C         u0         {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H       u[1,2]     {1,[S,D,B]}
3 *4 H         u0         {1,S}
4 *1 [H,C,N,S] u[1,2,3,4] {6,[S,D,T,B]}
5    C         ux         {1,[S,B]}
6    R!H       ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 39,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_6R!H->S",
    group = 
"""
1 *2 C         u0         {2,S} {3,S} {5,S}
2 *3 C         u1         {1,S}
3 *4 H         u0         {1,S}
4 *1 [H,C,N,S] u[1,2,3,4] {6,S}
5    C         u0         {1,S}
6    S         ux         {4,S}
""",
    kinetics = None,
)

entry(
    index = 40,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_6R!H->S_Ext-2R!H-R",
    group = 
"""
1 *2 C         u0         r0 {2,S} {3,S} {5,S}
2 *3 C         u1         r0 {1,S} {7,[S,D,T,B]}
3 *4 H         u0         r0 {1,S}
4 *1 [H,C,N,S] u[1,2,3,4] r0 {6,S}
5    C         u0         r0 {1,S}
6    S         ux         r0 {4,S}
7    R!H       ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 41,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S",
    group = 
"""
1 *2 C                      u0         {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H                    u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 [H,C,N,S]              u[1,2,3,4] {6,[S,D,T,B]}
5    C                      ux         {1,[S,B]}
6    [I,Br,F,Cl,O,P,C,N,Si] ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 42,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C",
    group = 
"""
1 *2 C                      u0         {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H                    u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 C                      u[1,2,3,4] {6,[S,D,T,B]}
5    C                      ux         {1,[S,B]}
6    [I,Br,F,Cl,O,P,C,N,Si] ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 43,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C",
    group = 
"""
1 *2 C                      u0     {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H                    u[1,2] {1,[S,D,B]}
3 *4 H                      u0     {1,S}
4 *1 C                      u1     {6,T}
5    C                      ux     {1,[S,B]}
6    [I,Br,F,Cl,O,P,C,N,Si] u0     {4,T}
""",
    kinetics = None,
)

entry(
    index = 44,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C",
    group = 
"""
1 *2 C                      u0         {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H                    u[1,2]     {1,[S,D,B]}
3 *4 H                      u0         {1,S}
4 *1 C                      u[1,2,3,4] {6,[S,D,B]}
5    C                      ux         {1,[S,B]}
6    [I,Br,F,Cl,O,P,C,N,Si] ux         {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 45,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {6,[S,D,B]}
5    C   ux         {1,[S,B]}
6    C   ux         {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 46,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_1R!H-inRing",
    group = 
"""
1 *2 C   u0     r1 {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1     {6,[S,D,B]}
5    C   ux     {1,[S,B]}
6    C   u0     {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 47,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing",
    group = 
"""
1 *2 C   u0         r0 {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {6,[S,D,B]}
5    C   ux         {1,[S,B]}
6    C   ux         {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 48,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Ext-4C-R",
    group = 
"""
1 *2 C   u0         r0 {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {6,[S,D,B]} {7,[S,D,T,B]}
5    C   ux         {1,[S,B]}
6    C   ux         {4,[S,D,B]}
7    R!H ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 49,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Ext-4C-R_2R!H->C",
    group = 
"""
1 *2 C   u0         r0 {2,S} {3,S} {5,S}
2 *3 C   u1         {1,S}
3 *4 H   u0         {1,S}
4 *1 C   u[1,2,3,4] {6,[S,D,B]} {7,[S,D,T,B]}
5    C   u0         {1,S}
6    C   ux         {4,[S,D,B]}
7    R!H ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 50,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Ext-4C-R_2R!H->C_Ext-4C-R",
    group = 
"""
1 *2 C   u0         r0 {2,S} {3,S} {5,S}
2 *3 C   u1         r0 {1,S}
3 *4 H   u0         r0 {1,S}
4 *1 C   u[1,2,3,4] r0 {6,[S,D,B]} {7,[S,D,T,B]} {8,[S,D,T,B]}
5    C   u0         r0 {1,S}
6    C   ux         r0 {4,[S,D,B]}
7    R!H ux         {4,[S,D,T,B]}
8    R!H ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 51,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Ext-4C-R_N-2R!H->C",
    group = 
"""
1 *2 C u0     r0 {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 S u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u1     {6,S} {7,S}
5    C ux     {1,[S,B]}
6    C u0     {4,S}
7    C u0     {4,S}
""",
    kinetics = None,
)

entry(
    index = 52,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Ext-4C-R_N-2R!H->C_Ext-7R!H-R_Ext-6C-R",
    group = 
"""
1 *2 C   u0     r0 {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 S   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1     {6,S} {7,S}
5    C   ux     {1,[S,B]}
6    C   u0     {4,S} {9,[S,D,T,B]}
7    C   u0     r0 {4,S} {8,D}
8    C   u0     r0 {7,D}
9    R!H ux     {6,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 53,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Sp-6C-4C",
    group = 
"""
1 *2 C u0 r0 {2,S} {3,S} {5,S}
2 *3 C u1 {1,S}
3 *4 H u0 {1,S}
4 *1 C u1 {6,S}
5    C u0 {1,S}
6    C u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 54,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Sp-6C-4C_Ext-6C-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S} {5,S}
2 *3 C   u1 r0 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 C   u1 r0 {6,S}
5    C   u0 r0 {1,S}
6    C   u0 r0 {4,S} {7,[S,D,T,B]}
7    R!H ux {6,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 55,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_N-Sp-6C-4C",
    group = 
"""
1 *2 C u0         r0 {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 C u[1,2]     {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] {6,D}
5    C ux         {1,[S,B]}
6    C ux         {4,D}
""",
    kinetics = None,
)

entry(
    index = 56,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_N-6BrCClFINOPSi->C",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H u1         {1,[S,D,B]}
3 *4 H   u0         r0 {1,S}
4 *1 C   u[1,2,3,4] {6,[S,D,B]}
5    C   u0         {1,[S,B]}
6    O   ux         {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 57,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_N-4CHNS->C",
    group = 
"""
1 *2 C                      u0         {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 R!H                    u1         {1,[S,D,B]}
3 *4 H                      u0         r0 {1,S}
4 *1 S                      u[1,2,3,4] {6,[S,D,T,B]}
5    C                      u0         {1,[S,B]}
6    [I,Br,F,Cl,O,P,C,N,Si] ux         {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 58,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_4CHNS->C",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 C u1         {1,[S,D,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4]
5    C u0         {1,[S,B]}
""",
    kinetics = None,
)

entry(
    index = 59,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_4CHNS->C_4C-u1",
    group = 
"""
1 *2 C u0 {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 C u1 {1,[S,D,B]}
3 *4 H u0 r0 {1,S}
4 *1 C u1
5    C u0 {1,[S,B]}
""",
    kinetics = None,
)

entry(
    index = 60,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_4CHNS->C_N-4C-u1",
    group = 
"""
1 *2 C u0 {2,[S,D,B]} {3,S} {5,[S,B]}
2 *3 C u1 {1,[S,D,B]}
3 *4 H u0 r0 {1,S}
4 *1 C u2
5    C u0 {1,[S,B]}
""",
    kinetics = None,
)

entry(
    index = 61,
    label = "Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_N-4CHNS->C",
    group = 
"""
1 *2 C     u0         r0 {2,S} {3,S} {5,S}
2 *3 C     u[1,2]     r0 {1,S}
3 *4 H     u0         {1,S}
4 *1 [H,S] u[1,2,3,4] r0
5    C     ux         r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 62,
    label = "Root_Ext-2R!H-R",
    group = 
"""
1 *2 C   u0         {2,[S,D,B]} {3,S}
2 *3 R!H u[1,2]     {1,[S,D,B]} {5,[S,D,T,B]}
3 *4 H   u0         {1,S}
4 *1 R   u[1,2,3,4]
5    R!H ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 63,
    label = "Root_Ext-2R!H-R_2R!H->C",
    group = 
"""
1 *2 C u0         {2,S} {3,S}
2 *3 C u[1,2]     {1,S} {5,[S,D,T,B]}
3 *4 H u0         {1,S}
4 *1 R u[1,2,3,4]
5    C ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 64,
    label = "Root_Ext-2R!H-R_2R!H->C_4R->C",
    group = 
"""
1 *2 C u0         r0 {2,S} {3,S}
2 *3 C u[1,2]     r0 {1,S} {5,[S,D,T,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] r0
5    C ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 65,
    label = "Root_Ext-2R!H-R_2R!H->C_N-4R->C",
    group = 
"""
1 *2 C       u0         r0 {2,S} {3,S}
2 *3 C       u[1,2]     r0 {1,S} {5,[S,D,T,B]}
3 *4 H       u0         {1,S}
4 *1 [H,N,O] u[1,2,3,4] r0
5    C       ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 66,
    label = "Root_Ext-2R!H-R_N-2R!H->C",
    group = 
"""
1 *2 C u0         {2,[S,D,B]} {3,S}
2 *3 N u[1,2]     {1,[S,D,B]} {5,[S,D,T,B]}
3 *4 H u0         {1,S}
4 *1 R u[1,2,3,4]
5    O ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 67,
    label = "Root_Ext-2R!H-R_N-2R!H->C_4R->H",
    group = 
"""
1 *2 C u0         r0 {2,D} {3,S}
2 *3 N u[1,2]     r0 {1,D} {5,[S,D,T,B]}
3 *4 H u0         {1,S}
4 *1 H u[1,2,3,4] r0
5    O ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 68,
    label = "Root_Ext-2R!H-R_N-2R!H->C_N-4R->H",
    group = 
"""
1 *2 C       u0         {2,[S,D,B]} {3,S}
2 *3 N       u[1,2]     {1,[S,D,B]} {5,[S,D,T,B]}
3 *4 H       u0         {1,S}
4 *1 [C,N,O] u[1,2,3,4]
5    O       ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 69,
    label = "Root_Ext-2R!H-R_N-2R!H->C_N-4R->H_4CNO->O",
    group = 
"""
1 *2 C u0 {2,[S,D,B]} {3,S}
2 *3 N u1 {1,[S,D,B]} {5,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1
5    O u0 r0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 70,
    label = "Root_Ext-2R!H-R_N-2R!H->C_N-4R->H_N-4CNO->O",
    group = 
"""
1 *2 C     u0         {2,D} {3,S}
2 *3 N     u[1,2]     {1,D} {5,[S,D,T,B]}
3 *4 H     u0         {1,S}
4 *1 [C,N] u[1,2,3,4]
5    O     ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 71,
    label = "Root_Ext-2R!H-R_N-2R!H->C_N-4R->H_N-4CNO->O_4CN->C",
    group = 
"""
1 *2 C u0         r0 {2,D} {3,S}
2 *3 N u[1,2]     r0 {1,D} {5,[S,D,T,B]}
3 *4 H u0         {1,S}
4 *1 C u[1,2,3,4] r0
5    O ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 72,
    label = "Root_Ext-2R!H-R_N-2R!H->C_N-4R->H_N-4CNO->O_N-4CN->C",
    group = 
"""
1 *2 C u0         r0 {2,D} {3,S}
2 *3 N u[1,2]     r0 {1,D} {5,[S,D,T,B]}
3 *4 H u0         {1,S}
4 *1 N u[1,2,3,4] r0
5    O ux         {2,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 73,
    label = "Root_4R->H",
    group = 
"""
1 *2 R!H u0         {2,[S,D,B]} {3,S}
2 *3 R!H u[1,2]     {1,[S,D,B]}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 74,
    label = "Root_4R->H_Sp-2R!H-1R!H",
    group = 
"""
1 *2 R!H u0         {2,S} {3,S}
2 *3 R!H u[1,2]     {1,S}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 75,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1",
    group = 
"""
1 *2 R!H u0         {2,S} {3,S}
2 *3 R!H u1         {1,S}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 76,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_1R!H->O",
    group = 
"""
1 *2 O   u0         {2,S} {3,S}
2 *3 R!H u1         {1,S}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 77,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_1R!H->O_2R!H->C",
    group = 
"""
1 *2 O u0         r0 {2,S} {3,S}
2 *3 C u1         r0 {1,S}
3 *4 H u0         {1,S}
4 *1 H u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 78,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_1R!H->O_N-2R!H->C",
    group = 
"""
1 *2 O     u0         r0 {2,S} {3,S}
2 *3 [N,O] u1         r0 {1,S}
3 *4 H     u0         {1,S}
4 *1 H     u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 79,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O",
    group = 
"""
1 *2 [C,N] u0         {2,S} {3,S}
2 *3 R!H   u1         {1,S}
3 *4 H     u0         {1,S}
4 *1 H     u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 80,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C",
    group = 
"""
1 *2 C   u0         {2,S} {3,S}
2 *3 R!H u1         {1,S}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 81,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_2R!H->C",
    group = 
"""
1 *2 C u0 {2,S} {3,S}
2 *3 C u1 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 H u1
""",
    kinetics = None,
)

entry(
    index = 82,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_N-2R!H->C",
    group = 
"""
1 *2 C     u0         {2,S} {3,S}
2 *3 [N,O] u1         {1,S}
3 *4 H     u0         {1,S}
4 *1 H     u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 83,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_N-2R!H->C_2NO->N",
    group = 
"""
1 *2 C u0         r0 {2,S} {3,S}
2 *3 N u1         r0 {1,S}
3 *4 H u0         {1,S}
4 *1 H u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 84,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_N-2R!H->C_N-2NO->N",
    group = 
"""
1 *2 C u0         r0 {2,S} {3,S}
2 *3 O u1         r0 {1,S}
3 *4 H u0         {1,S}
4 *1 H u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 85,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_N-1CN->C",
    group = 
"""
1 *2 N   u0         {2,S} {3,S}
2 *3 R!H u1         {1,S}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 86,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_N-1CN->C_2R!H->C",
    group = 
"""
1 *2 N u0 {2,S} {3,S}
2 *3 C u1 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 H u1
""",
    kinetics = None,
)

entry(
    index = 87,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_N-1CN->C_N-2R!H->C",
    group = 
"""
1 *2 N     u0         {2,S} {3,S}
2 *3 [N,O] u1         {1,S}
3 *4 H     u0         {1,S}
4 *1 H     u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 88,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_N-1CN->C_N-2R!H->C_2NO->N",
    group = 
"""
1 *2 N u0         r0 {2,S} {3,S}
2 *3 N u1         r0 {1,S}
3 *4 H u0         {1,S}
4 *1 H u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 89,
    label = "Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_N-1CN->C_N-2R!H->C_N-2NO->N",
    group = 
"""
1 *2 N u0         r0 {2,S} {3,S}
2 *3 O u1         r0 {1,S}
3 *4 H u0         {1,S}
4 *1 H u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 90,
    label = "Root_4R->H_Sp-2R!H-1R!H_N-2R!H-u1",
    group = 
"""
1 *2 R!H u0         r0 {2,S} {3,S}
2 *3 R!H u2         r0 {1,S}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 91,
    label = "Root_4R->H_N-Sp-2R!H-1R!H",
    group = 
"""
1 *2 R!H u0         {2,D} {3,S}
2 *3 R!H u[1,2]     {1,D}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 92,
    label = "Root_4R->H_N-Sp-2R!H-1R!H_1R!H->C",
    group = 
"""
1 *2 C   u0         r0 {2,D} {3,S}
2 *3 R!H u1         r0 {1,D}
3 *4 H   u0         {1,S}
4 *1 H   u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 93,
    label = "Root_4R->H_N-Sp-2R!H-1R!H_N-1R!H->C",
    group = 
"""
1 *2 N   u0     {2,D} {3,S}
2 *3 R!H u[1,2] {1,D}
3 *4 H   u0     {1,S}
4 *1 H   u1    
""",
    kinetics = None,
)

entry(
    index = 94,
    label = "Root_4R->H_N-Sp-2R!H-1R!H_N-1R!H->C_2R!H->C",
    group = 
"""
1 *2 N u0     {2,D} {3,S}
2 *3 C u[1,2] {1,D}
3 *4 H u0     r0 {1,S}
4 *1 H u1    
""",
    kinetics = None,
)

entry(
    index = 95,
    label = "Root_4R->H_N-Sp-2R!H-1R!H_N-1R!H->C_N-2R!H->C",
    group = 
"""
1 *2 N u0     {2,D} {3,S}
2 *3 N u[1,2] {1,D}
3 *4 H u0     r0 {1,S}
4 *1 H u1    
""",
    kinetics = None,
)

entry(
    index = 96,
    label = "Root_N-4R->H",
    group = 
"""
1 *2 R!H       u0         {2,[S,D,B]} {3,S}
2 *3 R!H       u[1,2]     {1,[S,D,B]}
3 *4 H         u0         {1,S}
4 *1 [C,O,N,S] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 97,
    label = "Root_N-4R->H_4CNOS-u1",
    group = 
"""
1 *2 R!H       u0     {2,[S,D,B]} {3,S}
2 *3 R!H       u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u1    
""",
    kinetics = None,
)

entry(
    index = 98,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O",
    group = 
"""
1 *2 O         u0     {2,[S,D,B]} {3,S}
2 *3 R!H       u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u1    
""",
    kinetics = None,
)

entry(
    index = 99,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C",
    group = 
"""
1 *2 O         u0     {2,[S,D,B]} {3,S}
2 *3 C         u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u1    
""",
    kinetics = None,
)

entry(
    index = 100,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R",
    group = 
"""
1 *2 O         u0     {2,[S,D,B]} {3,S}
2 *3 C         u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u1     {5,[S,D,T,B]}
5    R!H       ux     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 101,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_Sp-5R!H=4CCNNOOSS",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,D}
5    R!H u0     {4,D}
""",
    kinetics = None,
)

entry(
    index = 102,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_Sp-5R!H=4CCNNOOSS_5R!H->C",
    group = 
"""
1 *2 O u0     r0 {2,[S,D,B]} {3,S}
2 *3 C u[1,2] r0 {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u1     r0 {5,D}
5    C u0     {4,D}
""",
    kinetics = None,
)

entry(
    index = 103,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_Sp-5R!H=4CCNNOOSS_N-5R!H->C",
    group = 
"""
1 *2 O u0     r0 {2,[S,D,B]} {3,S}
2 *3 C u[1,2] r0 {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u1     r0 {5,D}
5    O u0     {4,D}
""",
    kinetics = None,
)

entry(
    index = 104,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS",
    group = 
"""
1 *2 O         u0     {2,[S,D,B]} {3,S}
2 *3 C         u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u1     {5,[S,T,B]}
5    R!H       ux     {4,[S,T,B]}
""",
    kinetics = None,
)

entry(
    index = 105,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_Ext-4CNOS-R",
    group = 
"""
1 *2 O   u0 {2,S} {3,S}
2 *3 C   u1 {1,S}
3 *4 H   u0 {1,S}
4 *1 C   u1 {5,S} {6,[S,D,T,B]}
5    C   u0 {4,S}
6    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 106,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_Ext-4CNOS-R_Ext-4CNOS-R",
    group = 
"""
1 *2 O   u0 {2,S} {3,S}
2 *3 C   u1 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 C   u1 {5,S} {6,[S,D,T,B]} {7,[S,D,T,B]}
5    C   u0 r0 {4,S}
6    R!H ux {4,[S,D,T,B]}
7    R!H ux {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 107,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_Ext-5R!H-R",
    group = 
"""
1 *2 O         u0     {2,[S,D,B]} {3,S}
2 *3 C         u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u1     {5,[S,T,B]}
5    R!H       ux     {4,[S,T,B]} {6,[S,D,T,B]}
6    R!H       ux     {5,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 108,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_4CNOS->C",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,[S,T,B]}
5    R!H ux     {4,[S,T,B]}
""",
    kinetics = None,
)

entry(
    index = 109,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_4CNOS->C_Sp-5R!H-4C",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,S}
5    R!H ux     {4,S}
""",
    kinetics = None,
)

entry(
    index = 110,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_4CNOS->C_Sp-5R!H-4C_5R!H->C",
    group = 
"""
1 *2 O u0     {2,[S,D,B]} {3,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u1     {5,S}
5    C ux     {4,S}
""",
    kinetics = None,
)

entry(
    index = 111,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_4CNOS->C_Sp-5R!H-4C_N-5R!H->C",
    group = 
"""
1 *2 O u0     {2,[S,D,B]} {3,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u1     {5,S}
5    O ux     {4,S}
""",
    kinetics = None,
)

entry(
    index = 112,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_4CNOS->C_N-Sp-5R!H-4C",
    group = 
"""
1 *2 O   u0 r0 {2,S} {3,S}
2 *3 C   u1 r0 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 C   u1 r0 {5,T}
5    R!H u0 r0 {4,T}
""",
    kinetics = None,
)

entry(
    index = 113,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 O   u1     {5,[S,T,B]}
5    R!H ux     {4,[S,T,B]}
""",
    kinetics = None,
)

entry(
    index = 114,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_5R!H-u0",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 C   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 O   u1     {5,[S,T,B]}
5    R!H u0     {4,[S,T,B]}
""",
    kinetics = None,
)

entry(
    index = 115,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_5R!H-u0_5R!H->C",
    group = 
"""
1 *2 O u0     {2,[S,D,B]} {3,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 O u1     {5,[S,T,B]}
5    C u0     {4,[S,T,B]}
""",
    kinetics = None,
)

entry(
    index = 116,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_5R!H-u0_N-5R!H->C",
    group = 
"""
1 *2 O u0     {2,[S,D,B]} {3,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 O u1     {5,[S,T,B]}
5    O u0     {4,[S,T,B]}
""",
    kinetics = None,
)

entry(
    index = 117,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_N-5R!H-u0",
    group = 
"""
1 *2 O   u0 r0 {2,S} {3,S}
2 *3 C   u1 r0 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 O   u1 r0 {5,S}
5    R!H u1 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 118,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_4CNOS->C",
    group = 
"""
1 *2 O u0     {2,[S,D,B]} {3,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 C u1    
""",
    kinetics = None,
)

entry(
    index = 119,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_N-4CNOS->C",
    group = 
"""
1 *2 O u0     {2,[S,D,B]} {3,S}
2 *3 C u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 120,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C",
    group = 
"""
1 *2 O         u0     {2,[S,D,B]} {3,S}
2 *3 [N,O,S]   u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u1    
""",
    kinetics = None,
)

entry(
    index = 121,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_4CNOS->O",
    group = 
"""
1 *2 O       u0     {2,[S,D,B]} {3,S}
2 *3 [N,O,S] u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 O       u1    
""",
    kinetics = None,
)

entry(
    index = 122,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_4CNOS->O_Ext-4O-R",
    group = 
"""
1 *2 O       u0     {2,[S,D,B]} {3,S}
2 *3 [N,O,S] u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 O       u1     {5,S}
5    R!H     u0     {4,S}
""",
    kinetics = None,
)

entry(
    index = 123,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_4CNOS->O_Ext-4O-R_2NOS->N",
    group = 
"""
1 *2 O   u0     r0 {2,[S,D,B]} {3,S}
2 *3 N   u[1,2] r0 {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 O   u1     r0 {5,S}
5    R!H u0     r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 124,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_4CNOS->O_Ext-4O-R_N-2NOS->N",
    group = 
"""
1 *2 O   u0     r0 {2,[S,D,B]} {3,S}
2 *3 O   u[1,2] r0 {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 O   u1     r0 {5,S}
5    R!H u0     r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 125,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O",
    group = 
"""
1 *2 O       u0     {2,[S,D,B]} {3,S}
2 *3 [N,O,S] u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N]   u1    
""",
    kinetics = None,
)

entry(
    index = 126,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_4CN->C",
    group = 
"""
1 *2 O       u0 {2,S} {3,S}
2 *3 [N,O,S] u1 {1,S}
3 *4 H       u0 r0 {1,S}
4 *1 C       u1
""",
    kinetics = None,
)

entry(
    index = 127,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C",
    group = 
"""
1 *2 O       u0     {2,[S,D,B]} {3,S}
2 *3 [N,O,S] u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 N       u1    
""",
    kinetics = None,
)

entry(
    index = 128,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_Ext-4N-R",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 O   u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 N   u1     {5,[S,D,T,B]}
5    R!H ux     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 129,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_Ext-4N-R_5R!H->N",
    group = 
"""
1 *2 O u0 {2,S} {3,S}
2 *3 O u1 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 N u1 {5,[S,D,T,B]}
5    N u0 r0 {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 130,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_Ext-4N-R_N-5R!H->N",
    group = 
"""
1 *2 O                      u0     {2,[S,D,B]} {3,S}
2 *3 O                      u[1,2] {1,[S,D,B]}
3 *4 H                      u0     {1,S}
4 *1 N                      u1     {5,[S,D,T,B]}
5    [I,Br,F,Cl,O,P,S,C,Si] ux     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 131,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_Ext-4N-R_N-5R!H->N_5BrCClFIOPSSi->C",
    group = 
"""
1 *2 O u0     r0 {2,[S,D,B]} {3,S}
2 *3 O u[1,2] r0 {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 N u1     r0 {5,[S,D,T,B]}
5    C ux     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 132,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_Ext-4N-R_N-5R!H->N_N-5BrCClFIOPSSi->C",
    group = 
"""
1 *2 O u0     r0 {2,[S,D,B]} {3,S}
2 *3 O u[1,2] r0 {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 N u1     r0 {5,[S,D,T,B]}
5    O ux     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 133,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_2NOS->N",
    group = 
"""
1 *2 O u0     {2,[S,D,B]} {3,S}
2 *3 N u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 N u1    
""",
    kinetics = None,
)

entry(
    index = 134,
    label = "Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_N-2NOS->N",
    group = 
"""
1 *2 O u0     {2,[S,D,B]} {3,S}
2 *3 O u[1,2] {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 N u1    
""",
    kinetics = None,
)

entry(
    index = 135,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O",
    group = 
"""
1 *2 [C,N,S]   u0     {2,[S,D,B]} {3,S}
2 *3 R!H       u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u1    
""",
    kinetics = None,
)

entry(
    index = 136,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 R!H     u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 O       u1    
""",
    kinetics = None,
)

entry(
    index = 137,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 R!H     u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 O       u1     {5,[S,D,T,B]}
5    O       ux     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 138,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 R!H     u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 O       u1     {5,[S,D,T,B]}
5    O       u0     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 139,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_Sp-2R!H-1CNS",
    group = 
"""
1 *2 N   u0     {2,S} {3,S}
2 *3 R!H u[1,2] {1,S}
3 *4 H   u0     {1,S}
4 *1 O   u1     {5,[S,D,T,B]}
5    O   u0     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 140,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_Sp-2R!H-1CNS_2R!H->N",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 N u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 O u1     {5,[S,D,T,B]}
5    O u0     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 141,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_Sp-2R!H-1CNS_2R!H->N_2N-u1",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 N u1 r0 {1,S}
3 *4 H u0 {1,S}
4 *1 O u1 r0 {5,[S,D,T,B]}
5    O u0 {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 142,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_Sp-2R!H-1CNS_2R!H->N_N-2N-u1",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 N u2 r0 {1,S}
3 *4 H u0 {1,S}
4 *1 O u1 r0 {5,[S,D,T,B]}
5    O u0 {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 143,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_Sp-2R!H-1CNS_N-2R!H->N",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 O u[1,2] {1,S}
3 *4 H u0     r0 {1,S}
4 *1 O u1     {5,S}
5    O u0     r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 144,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_N-Sp-2R!H-1CNS",
    group = 
"""
1 *2 [C,N,S] u0 {2,D} {3,S}
2 *3 N       u1 {1,D}
3 *4 H       u0 {1,S}
4 *1 O       u1 {5,S}
5    O       u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 145,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_N-Sp-2R!H-1CNS_1CNS->C",
    group = 
"""
1 *2 C u0 {2,D} {3,S}
2 *3 N u1 {1,D}
3 *4 H u0 r0 {1,S}
4 *1 O u1 {5,S}
5    O u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 146,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_N-Sp-2R!H-1CNS_N-1CNS->C",
    group = 
"""
1 *2 N u0 {2,D} {3,S}
2 *3 N u1 {1,D}
3 *4 H u0 r0 {1,S}
4 *1 O u1 {5,S}
5    O u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 147,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_N-5R!H-u0",
    group = 
"""
1 *2 [C,N,S] u0       {2,[S,D,B]} {3,S}
2 *3 R!H     u[1,2]   {1,[S,D,B]}
3 *4 H       u0       {1,S}
4 *1 O       u1       {5,[S,D,T,B]}
5    O       u[1,2,3] {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 148,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_N-5R!H-u0_Sp-2R!H-1CNS",
    group = 
"""
1 *2 [C,N,S] u0 r0 {2,S} {3,S}
2 *3 R!H     u1 r0 {1,S}
3 *4 H       u0 {1,S}
4 *1 O       u1 r0 {5,[S,D,T,B]}
5    O       u1 {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 149,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_N-5R!H-u0_N-Sp-2R!H-1CNS",
    group = 
"""
1 *2 [C,N,S] u0       {2,D} {3,S}
2 *3 R!H     u[1,2]   {1,D}
3 *4 H       u0       {1,S}
4 *1 O       u1       {5,S}
5    O       u[1,2,3] {4,S}
""",
    kinetics = None,
)

entry(
    index = 150,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_N-5R!H-u0_N-Sp-2R!H-1CNS_1CNS->C",
    group = 
"""
1 *2 C   u0       {2,D} {3,S}
2 *3 R!H u[1,2]   {1,D}
3 *4 H   u0       r0 {1,S}
4 *1 O   u1       {5,S}
5    O   u[1,2,3] r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 151,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_N-5R!H-u0_N-Sp-2R!H-1CNS_N-1CNS->C",
    group = 
"""
1 *2 N   u0       {2,D} {3,S}
2 *3 R!H u[1,2]   {1,D}
3 *4 H   u0       r0 {1,S}
4 *1 O   u1       {5,S}
5    O   u[1,2,3] r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 152,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS",
    group = 
"""
1 *2 [C,N,S] u0     {2,S} {3,S}
2 *3 R!H     u[1,2] {1,S}
3 *4 H       u0     {1,S}
4 *1 O       u1    
""",
    kinetics = None,
)

entry(
    index = 153,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_1CNS->C",
    group = 
"""
1 *2 C   u0 {2,S} {3,S}
2 *3 R!H u1 {1,S}
3 *4 H   u0 {1,S}
4 *1 O   u1
""",
    kinetics = None,
)

entry(
    index = 154,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_1CNS->C_2R!H->C",
    group = 
"""
1 *2 C u0 {2,S} {3,S}
2 *3 C u1 {1,S}
3 *4 H u0 {1,S}
4 *1 O u1
""",
    kinetics = None,
)

entry(
    index = 155,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_1CNS->C_N-2R!H->C",
    group = 
"""
1 *2 C     u0 {2,S} {3,S}
2 *3 [N,O] u1 {1,S}
3 *4 H     u0 {1,S}
4 *1 O     u1
""",
    kinetics = None,
)

entry(
    index = 156,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C",
    group = 
"""
1 *2 N   u0     {2,S} {3,S}
2 *3 R!H u[1,2] {1,S}
3 *4 H   u0     {1,S}
4 *1 O   u1    
""",
    kinetics = None,
)

entry(
    index = 157,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_2R!H->N",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 N u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 158,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_2R!H->N_2N-u1",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 N u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 r0
""",
    kinetics = None,
)

entry(
    index = 159,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_2R!H->N_N-2N-u1",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 N u2 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 r0
""",
    kinetics = None,
)

entry(
    index = 160,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->N",
    group = 
"""
1 *2 N     u0 {2,S} {3,S}
2 *3 [C,O] u1 {1,S}
3 *4 H     u0 {1,S}
4 *1 O     u1
""",
    kinetics = None,
)

entry(
    index = 161,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->N_2CO->C",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 C u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 r0
""",
    kinetics = None,
)

entry(
    index = 162,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->N_N-2CO->C",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 O u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u1 r0
""",
    kinetics = None,
)

entry(
    index = 163,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_N-Sp-2R!H-1CNS",
    group = 
"""
1 *2 [C,N,S] u0     {2,D} {3,S}
2 *3 R!H     u[1,2] {1,D}
3 *4 H       u0     {1,S}
4 *1 O       u1    
""",
    kinetics = None,
)

entry(
    index = 164,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_N-Sp-2R!H-1CNS_1CNS->C",
    group = 
"""
1 *2 C   u0 r0 {2,D} {3,S}
2 *3 R!H u1 r0 {1,D}
3 *4 H   u0 r0 {1,S}
4 *1 O   u1 r0
""",
    kinetics = None,
)

entry(
    index = 165,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_N-Sp-2R!H-1CNS_N-1CNS->C",
    group = 
"""
1 *2 N   u0     {2,D} {3,S}
2 *3 R!H u[1,2] {1,D}
3 *4 H   u0     {1,S}
4 *1 O   u1    
""",
    kinetics = None,
)

entry(
    index = 166,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_N-Sp-2R!H-1CNS_N-1CNS->C_2R!H->C",
    group = 
"""
1 *2 N u0     {2,D} {3,S}
2 *3 C u[1,2] {1,D}
3 *4 H u0     {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 167,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_N-Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C",
    group = 
"""
1 *2 N u0     {2,D} {3,S}
2 *3 N u[1,2] {1,D}
3 *4 H u0     {1,S}
4 *1 O u1    
""",
    kinetics = None,
)

entry(
    index = 168,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 R!H     u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1    
""",
    kinetics = None,
)

entry(
    index = 169,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 R!H     u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     {5,[S,D,T,B]}
5    R!H     ux     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 170,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_Sp-5R!H#4CCCNNNSSS",
    group = 
"""
1 *2 [C,N,S] u0 {2,[S,D,B]} {3,S}
2 *3 R!H     u1 {1,[S,D,B]}
3 *4 H       u0 r0 {1,S}
4 *1 [C,N,S] u1 {5,T}
5    R!H     u0 r0 {4,T}
""",
    kinetics = None,
)

entry(
    index = 171,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 R!H     u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     {5,[S,D,B]}
5    R!H     ux     {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 172,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_2R!H->S",
    group = 
"""
1 *2 [C,N,S] u0     r0 {2,[S,D,B]} {3,S}
2 *3 S       u[1,2] r0 {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     r0 {5,[S,D,B]}
5    R!H     ux     {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 173,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 [C,N]   u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     {5,[S,D,B]}
5    R!H     ux     {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 174,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_5R!H->O",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 [C,N]   u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     {5,[S,D,B]}
5    O       ux     {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 175,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_5R!H->O_1CNS->C",
    group = 
"""
1 *2 C       u0     r0 {2,[S,D,B]} {3,S}
2 *3 [C,N]   u[1,2] r0 {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     r0 {5,[S,D,B]}
5    O       ux     {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 176,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_5R!H->O_N-1CNS->C",
    group = 
"""
1 *2 [N,S]   u0     r0 {2,[S,D,B]} {3,S}
2 *3 [C,N]   u[1,2] r0 {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     r0 {5,[S,D,B]}
5    O       ux     {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 177,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 C       u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     {5,[S,D,B]}
5    [C,S]   ux     {4,[S,D,B]}
""",
    kinetics = None,
)

entry(
    index = 178,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 C       u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     {5,S}
5    [C,S]   ux     {4,S}
""",
    kinetics = None,
)

entry(
    index = 179,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_Ext-4CNS-R",
    group = 
"""
1 *2 C   u0     {2,S} {3,S}
2 *3 C   u[1,2] {1,S}
3 *4 H   u0     {1,S}
4 *1 C   u1     {5,S} {6,[S,D,T,B]}
5    C   ux     {4,S}
6    R!H ux     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 180,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_Ext-4CNS-R_Ext-4CNS-R",
    group = 
"""
1 *2 C   u0     r0 {2,S} {3,S}
2 *3 C   u[1,2] r0 {1,S}
3 *4 H   u0     {1,S}
4 *1 C   u1     r0 {5,S} {6,[S,D,T,B]} {7,[S,D,T,B]}
5    C   ux     {4,S}
6    R!H ux     {4,[S,D,T,B]}
7    R!H ux     {4,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 181,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C",
    group = 
"""
1 *2 C u0 {2,S} {3,S}
2 *3 C u1 {1,S}
3 *4 H u0 {1,S}
4 *1 C u1 {5,S}
5    C u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 182,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C_Ext-5CS-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S}
2 *3 C   u1 r0 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 C   u1 r0 {5,S}
5    C   u0 r0 {4,S} {6,[S,D,T,B]}
6    R!H ux {5,[S,D,T,B]}
""",
    kinetics = None,
)

entry(
    index = 183,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_N-1CNS->C",
    group = 
"""
1 *2 S       u0     {2,[S,D,B]} {3,S}
2 *3 C       u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     {5,S}
5    [C,S]   ux     {4,S}
""",
    kinetics = None,
)

entry(
    index = 184,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_N-Sp-5CS-4CCNSS",
    group = 
"""
1 *2 [C,N,S] u0     r0 {2,S} {3,S}
2 *3 C       u[1,2] r0 {1,S}
3 *4 H       u0     {1,S}
4 *1 [C,N,S] u1     r0 {5,D}
5    [C,S]   ux     {4,D}
""",
    kinetics = None,
)

entry(
    index = 185,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 R!H     u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 C       u1    
""",
    kinetics = None,
)

entry(
    index = 186,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C",
    group = 
"""
1 *2 C   u0     {2,[S,D,B]} {3,S}
2 *3 R!H u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1    
""",
    kinetics = None,
)

entry(
    index = 187,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_Sp-2R!H-1C",
    group = 
"""
1 *2 C   u0     {2,S} {3,S}
2 *3 R!H u[1,2] {1,S}
3 *4 H   u0     {1,S}
4 *1 C   u1    
""",
    kinetics = None,
)

entry(
    index = 188,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_Sp-2R!H-1C_2R!H->C",
    group = 
"""
1 *2 C u0     r0 {2,S} {3,S}
2 *3 C u[1,2] r0 {1,S}
3 *4 H u0     r0 {1,S}
4 *1 C u1     r0
""",
    kinetics = None,
)

entry(
    index = 189,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_Sp-2R!H-1C_N-2R!H->C",
    group = 
"""
1 *2 C u0     r0 {2,S} {3,S}
2 *3 N u[1,2] r0 {1,S}
3 *4 H u0     r0 {1,S}
4 *1 C u1     r0
""",
    kinetics = None,
)

entry(
    index = 190,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_N-Sp-2R!H-1C",
    group = 
"""
1 *2 C   u0 {2,D} {3,S}
2 *3 R!H u1 {1,D}
3 *4 H   u0 {1,S}
4 *1 C   u1
""",
    kinetics = None,
)

entry(
    index = 191,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C",
    group = 
"""
1 *2 N   u0     {2,[S,D,B]} {3,S}
2 *3 R!H u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 C   u1    
""",
    kinetics = None,
)

entry(
    index = 192,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_2R!H->C",
    group = 
"""
1 *2 N u0 {2,[S,D,B]} {3,S}
2 *3 C u1 {1,[S,D,B]}
3 *4 H u0 {1,S}
4 *1 C u1
""",
    kinetics = None,
)

entry(
    index = 193,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_2R!H->C_Sp-2C-1N",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 C u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 C u1 r0
""",
    kinetics = None,
)

entry(
    index = 194,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_2R!H->C_N-Sp-2C-1N",
    group = 
"""
1 *2 N u0 r0 {2,D} {3,S}
2 *3 C u1 r0 {1,D}
3 *4 H u0 r0 {1,S}
4 *1 C u1 r0
""",
    kinetics = None,
)

entry(
    index = 195,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_N-2R!H->C",
    group = 
"""
1 *2 N     u0     {2,[S,D,B]} {3,S}
2 *3 [N,O] u[1,2] {1,[S,D,B]}
3 *4 H     u0     {1,S}
4 *1 C     u1    
""",
    kinetics = None,
)

entry(
    index = 196,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_N-2R!H->C_2NO-u1",
    group = 
"""
1 *2 N     u0 {2,[S,D,B]} {3,S}
2 *3 [N,O] u1 {1,[S,D,B]}
3 *4 H     u0 {1,S}
4 *1 C     u1
""",
    kinetics = None,
)

entry(
    index = 197,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_N-2R!H->C_2NO-u1_2NO->N",
    group = 
"""
1 *2 N u0 {2,[S,D,B]} {3,S}
2 *3 N u1 {1,[S,D,B]}
3 *4 H u0 {1,S}
4 *1 C u1
""",
    kinetics = None,
)

entry(
    index = 198,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_N-2R!H->C_2NO-u1_N-2NO->N",
    group = 
"""
1 *2 N u0 {2,[S,D,B]} {3,S}
2 *3 O u1 {1,[S,D,B]}
3 *4 H u0 {1,S}
4 *1 C u1
""",
    kinetics = None,
)

entry(
    index = 199,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_N-2R!H->C_N-2NO-u1",
    group = 
"""
1 *2 N     u0 r0 {2,S} {3,S}
2 *3 [N,O] u2 r0 {1,S}
3 *4 H     u0 r0 {1,S}
4 *1 C     u1 r0
""",
    kinetics = None,
)

entry(
    index = 200,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C",
    group = 
"""
1 *2 [C,N,S] u0     {2,[S,D,B]} {3,S}
2 *3 R!H     u[1,2] {1,[S,D,B]}
3 *4 H       u0     {1,S}
4 *1 N       u1    
""",
    kinetics = None,
)

entry(
    index = 201,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_Sp-2R!H-1CNS",
    group = 
"""
1 *2 N   u0     {2,S} {3,S}
2 *3 R!H u[1,2] {1,S}
3 *4 H   u0     {1,S}
4 *1 N   u1    
""",
    kinetics = None,
)

entry(
    index = 202,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_Sp-2R!H-1CNS_2R!H->N",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 N u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 N u1    
""",
    kinetics = None,
)

entry(
    index = 203,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_Sp-2R!H-1CNS_2R!H->N_2N-u1",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 N u1 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 N u1 r0
""",
    kinetics = None,
)

entry(
    index = 204,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_Sp-2R!H-1CNS_2R!H->N_N-2N-u1",
    group = 
"""
1 *2 N u0 r0 {2,S} {3,S}
2 *3 N u2 r0 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 N u1 r0
""",
    kinetics = None,
)

entry(
    index = 205,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_Sp-2R!H-1CNS_N-2R!H->N",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 O u[1,2] {1,S}
3 *4 H u0     {1,S}
4 *1 N u1    
""",
    kinetics = None,
)

entry(
    index = 206,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_N-Sp-2R!H-1CNS",
    group = 
"""
1 *2 [C,N,S] u0 {2,D} {3,S}
2 *3 N       u1 {1,D}
3 *4 H       u0 {1,S}
4 *1 N       u1
""",
    kinetics = None,
)

entry(
    index = 207,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_N-Sp-2R!H-1CNS_1CNS->C",
    group = 
"""
1 *2 C u0 {2,D} {3,S}
2 *3 N u1 {1,D}
3 *4 H u0 {1,S}
4 *1 N u1
""",
    kinetics = None,
)

entry(
    index = 208,
    label = "Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_N-Sp-2R!H-1CNS_N-1CNS->C",
    group = 
"""
1 *2 N u0 {2,D} {3,S}
2 *3 N u1 {1,D}
3 *4 H u0 {1,S}
4 *1 N u1
""",
    kinetics = None,
)

entry(
    index = 209,
    label = "Root_N-4R->H_N-4CNOS-u1",
    group = 
"""
1 *2 R!H       u0     {2,[S,D,B]} {3,S}
2 *3 R!H       u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u2    
""",
    kinetics = None,
)

entry(
    index = 210,
    label = "Root_N-4R->H_N-4CNOS-u1_1R!H->O",
    group = 
"""
1 *2 O         u0     {2,[S,D,B]} {3,S}
2 *3 R!H       u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u2    
""",
    kinetics = None,
)

entry(
    index = 211,
    label = "Root_N-4R->H_N-4CNOS-u1_1R!H->O_4CNOS->C",
    group = 
"""
1 *2 O   u0 {2,S} {3,S}
2 *3 R!H u1 {1,S}
3 *4 H   u0 r0 {1,S}
4 *1 C   u2
""",
    kinetics = None,
)

entry(
    index = 212,
    label = "Root_N-4R->H_N-4CNOS-u1_1R!H->O_N-4CNOS->C",
    group = 
"""
1 *2 O   u0     {2,[S,D,B]} {3,S}
2 *3 R!H u[1,2] {1,[S,D,B]}
3 *4 H   u0     {1,S}
4 *1 O   u2    
""",
    kinetics = None,
)

entry(
    index = 213,
    label = "Root_N-4R->H_N-4CNOS-u1_1R!H->O_N-4CNOS->C_2R!H->C",
    group = 
"""
1 *2 O u0     r0 {2,[S,D,B]} {3,S}
2 *3 C u[1,2] r0 {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 O u2     r0
""",
    kinetics = None,
)

entry(
    index = 214,
    label = "Root_N-4R->H_N-4CNOS-u1_1R!H->O_N-4CNOS->C_N-2R!H->C",
    group = 
"""
1 *2 O u0     r0 {2,[S,D,B]} {3,S}
2 *3 N u[1,2] r0 {1,[S,D,B]}
3 *4 H u0     {1,S}
4 *1 O u2     r0
""",
    kinetics = None,
)

entry(
    index = 215,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O",
    group = 
"""
1 *2 [C,N,S]   u0     {2,[S,D,B]} {3,S}
2 *3 R!H       u[1,2] {1,[S,D,B]}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u2    
""",
    kinetics = None,
)

entry(
    index = 216,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS",
    group = 
"""
1 *2 [C,N,S]   u0     {2,S} {3,S}
2 *3 R!H       u[1,2] {1,S}
3 *4 H         u0     {1,S}
4 *1 [C,O,N,S] u2    
""",
    kinetics = None,
)

entry(
    index = 217,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_1CNS->C",
    group = 
"""
1 *2 C         u0 {2,S} {3,S}
2 *3 R!H       u1 {1,S}
3 *4 H         u0 {1,S}
4 *1 [C,O,N,S] u2
""",
    kinetics = None,
)

entry(
    index = 218,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_1CNS->C_2R!H->C",
    group = 
"""
1 *2 C         u0 {2,S} {3,S}
2 *3 C         u1 {1,S}
3 *4 H         u0 r0 {1,S}
4 *1 [C,O,N,S] u2
""",
    kinetics = None,
)

entry(
    index = 219,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_1CNS->C_N-2R!H->C",
    group = 
"""
1 *2 C         u0 {2,S} {3,S}
2 *3 [N,O]     u1 {1,S}
3 *4 H         u0 r0 {1,S}
4 *1 [C,O,N,S] u2
""",
    kinetics = None,
)

entry(
    index = 220,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C",
    group = 
"""
1 *2 N   u0     {2,S} {3,S}
2 *3 R!H u[1,2] {1,S}
3 *4 H   u0     {1,S}
4 *1 O   u2    
""",
    kinetics = None,
)

entry(
    index = 221,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_2R!H->C",
    group = 
"""
1 *2 N u0     {2,S} {3,S}
2 *3 C u[1,2] {1,S}
3 *4 H u0     r0 {1,S}
4 *1 O u2    
""",
    kinetics = None,
)

entry(
    index = 222,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C",
    group = 
"""
1 *2 N     u0     {2,S} {3,S}
2 *3 [N,O] u[1,2] {1,S}
3 *4 H     u0     {1,S}
4 *1 O     u2    
""",
    kinetics = None,
)

entry(
    index = 223,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C_2NO-u1",
    group = 
"""
1 *2 N     u0 {2,S} {3,S}
2 *3 [N,O] u1 {1,S}
3 *4 H     u0 {1,S}
4 *1 O     u2
""",
    kinetics = None,
)

entry(
    index = 224,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C_2NO-u1_2NO->N",
    group = 
"""
1 *2 N u0 {2,S} {3,S}
2 *3 N u1 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u2
""",
    kinetics = None,
)

entry(
    index = 225,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C_2NO-u1_N-2NO->N",
    group = 
"""
1 *2 N u0 {2,S} {3,S}
2 *3 O u1 {1,S}
3 *4 H u0 r0 {1,S}
4 *1 O u2
""",
    kinetics = None,
)

entry(
    index = 226,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C_N-2NO-u1",
    group = 
"""
1 *2 N     u0 r0 {2,S} {3,S}
2 *3 [N,O] u2 r0 {1,S}
3 *4 H     u0 {1,S}
4 *1 O     u2 r0
""",
    kinetics = None,
)

entry(
    index = 227,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_N-Sp-2R!H-1CNS",
    group = 
"""
1 *2 [C,N,S] u0     {2,D} {3,S}
2 *3 R!H     u[1,2] {1,D}
3 *4 H       u0     {1,S}
4 *1 O       u2    
""",
    kinetics = None,
)

entry(
    index = 228,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_N-Sp-2R!H-1CNS_1CNS->C",
    group = 
"""
1 *2 C   u0 r0 {2,D} {3,S}
2 *3 R!H u1 r0 {1,D}
3 *4 H   u0 {1,S}
4 *1 O   u2 r0
""",
    kinetics = None,
)

entry(
    index = 229,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_N-Sp-2R!H-1CNS_N-1CNS->C",
    group = 
"""
1 *2 N   u0     {2,D} {3,S}
2 *3 R!H u[1,2] {1,D}
3 *4 H   u0     {1,S}
4 *1 O   u2    
""",
    kinetics = None,
)

entry(
    index = 230,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_N-Sp-2R!H-1CNS_N-1CNS->C_2R!H->C",
    group = 
"""
1 *2 N u0     {2,D} {3,S}
2 *3 C u[1,2] {1,D}
3 *4 H u0     r0 {1,S}
4 *1 O u2    
""",
    kinetics = None,
)

entry(
    index = 231,
    label = "Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_N-Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C",
    group = 
"""
1 *2 N u0     {2,D} {3,S}
2 *3 N u[1,2] {1,D}
3 *4 H u0     r0 {1,S}
4 *1 O u2    
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_Ext-1R!H-R
        L3: Root_Ext-1R!H-R_4R->O
            L4: Root_Ext-1R!H-R_4R->O_Ext-4O-R
                L5: Root_Ext-1R!H-R_4R->O_Ext-4O-R_Sp-5R!H-1R!H
                    L6: Root_Ext-1R!H-R_4R->O_Ext-4O-R_Sp-5R!H-1R!H_Ext-5R!H-R
                        L7: Root_Ext-1R!H-R_4R->O_Ext-4O-R_Sp-5R!H-1R!H_Ext-5R!H-R_Ext-1R!H-R
                            L8: Root_Ext-1R!H-R_4R->O_Ext-4O-R_Sp-5R!H-1R!H_Ext-5R!H-R_Ext-1R!H-R_Ext-8R!H-R
                    L6: Root_Ext-1R!H-R_4R->O_Ext-4O-R_Sp-5R!H-1R!H_Ext-1R!H-R
                L5: Root_Ext-1R!H-R_4R->O_Ext-4O-R_N-Sp-5R!H-1R!H
            L4: Root_Ext-1R!H-R_4R->O_Sp-5R!H-1R!H
                L5: Root_Ext-1R!H-R_4R->O_Sp-5R!H-1R!H_Ext-1R!H-R
            L4: Root_Ext-1R!H-R_4R->O_N-Sp-5R!H-1R!H
        L3: Root_Ext-1R!H-R_N-4R->O
            L4: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R
                L5: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C
                    L6: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R
                        L7: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_Sp-7R!H#4C
                        L7: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C
                            L8: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C
                                L9: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_Ext-4C-R
                                    L10: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_Ext-4C-R_Ext-4C-R
                                L9: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_Ext-7C-R
                                L9: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_Sp-7C-4C
                                L9: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_7R!H->C_N-Sp-7C-4C
                            L8: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_4CHNS->C_Ext-4C-R_N-Sp-7R!H#4C_N-7R!H->C
                L5: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_N-4CHNS->C
                    L6: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_N-4CHNS->C_4HS->H
                    L6: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_N-4CHNS->C_N-4HS->H
                        L7: Root_Ext-1R!H-R_N-4R->O_Ext-1R!H-R_N-4CHNS->C_N-4HS->H_Ext-4S-R_Ext-7R!H-R
            L4: Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H
                L5: Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R
                    L6: Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Ext-6R!H-R
                    L6: Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Ext-4CHNS-R
                        L7: Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Ext-4CHNS-R_Ext-4CHNS-R
                    L6: Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_Sp-6R!H-4CHNS
                    L6: Root_Ext-1R!H-R_N-4R->O_Sp-5R!H=1R!H_Ext-4CHNS-R_N-Sp-6R!H-4CHNS
            L4: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H
                L5: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R
                    L6: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_6R!H->S
                        L7: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_6R!H->S_Ext-2R!H-R
                    L6: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S
                        L7: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C
                            L8: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C
                            L8: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C
                                L9: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C
                                    L10: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_1R!H-inRing
                                    L10: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing
                                        L11: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Ext-4C-R
                                            L12: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Ext-4C-R_2R!H->C
                                                L13: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Ext-4C-R_2R!H->C_Ext-4C-R
                                            L12: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Ext-4C-R_N-2R!H->C
                                                L13: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Ext-4C-R_N-2R!H->C_Ext-7R!H-R_Ext-6C-R
                                        L11: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Sp-6C-4C
                                            L12: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_Sp-6C-4C_Ext-6C-R
                                        L11: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_6BrCClFINOPSi->C_N-1R!H-inRing_N-Sp-6C-4C
                                L9: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_4CHNS->C_N-Sp-6BrBrBrCCCClClClFFFIIINNNOOOPPPSiSiSi#4C_N-6BrCClFINOPSi->C
                        L7: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_Ext-4CHNS-R_N-6R!H->S_N-4CHNS->C
                L5: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_4CHNS->C
                    L6: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_4CHNS->C_4C-u1
                    L6: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_4CHNS->C_N-4C-u1
                L5: Root_Ext-1R!H-R_N-4R->O_N-Sp-5R!H=1R!H_N-4CHNS->C
    L2: Root_Ext-2R!H-R
        L3: Root_Ext-2R!H-R_2R!H->C
            L4: Root_Ext-2R!H-R_2R!H->C_4R->C
            L4: Root_Ext-2R!H-R_2R!H->C_N-4R->C
        L3: Root_Ext-2R!H-R_N-2R!H->C
            L4: Root_Ext-2R!H-R_N-2R!H->C_4R->H
            L4: Root_Ext-2R!H-R_N-2R!H->C_N-4R->H
                L5: Root_Ext-2R!H-R_N-2R!H->C_N-4R->H_4CNO->O
                L5: Root_Ext-2R!H-R_N-2R!H->C_N-4R->H_N-4CNO->O
                    L6: Root_Ext-2R!H-R_N-2R!H->C_N-4R->H_N-4CNO->O_4CN->C
                    L6: Root_Ext-2R!H-R_N-2R!H->C_N-4R->H_N-4CNO->O_N-4CN->C
    L2: Root_4R->H
        L3: Root_4R->H_Sp-2R!H-1R!H
            L4: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1
                L5: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_1R!H->O
                    L6: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_1R!H->O_2R!H->C
                    L6: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_1R!H->O_N-2R!H->C
                L5: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O
                    L6: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C
                        L7: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_2R!H->C
                        L7: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_N-2R!H->C
                            L8: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_N-2R!H->C_2NO->N
                            L8: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_1CN->C_N-2R!H->C_N-2NO->N
                    L6: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_N-1CN->C
                        L7: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_N-1CN->C_2R!H->C
                        L7: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_N-1CN->C_N-2R!H->C
                            L8: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_N-1CN->C_N-2R!H->C_2NO->N
                            L8: Root_4R->H_Sp-2R!H-1R!H_2R!H-u1_N-1R!H->O_N-1CN->C_N-2R!H->C_N-2NO->N
            L4: Root_4R->H_Sp-2R!H-1R!H_N-2R!H-u1
        L3: Root_4R->H_N-Sp-2R!H-1R!H
            L4: Root_4R->H_N-Sp-2R!H-1R!H_1R!H->C
            L4: Root_4R->H_N-Sp-2R!H-1R!H_N-1R!H->C
                L5: Root_4R->H_N-Sp-2R!H-1R!H_N-1R!H->C_2R!H->C
                L5: Root_4R->H_N-Sp-2R!H-1R!H_N-1R!H->C_N-2R!H->C
    L2: Root_N-4R->H
        L3: Root_N-4R->H_4CNOS-u1
            L4: Root_N-4R->H_4CNOS-u1_1R!H->O
                L5: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C
                    L6: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R
                        L7: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_Sp-5R!H=4CCNNOOSS
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_Sp-5R!H=4CCNNOOSS_5R!H->C
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_Sp-5R!H=4CCNNOOSS_N-5R!H->C
                        L7: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_Ext-4CNOS-R
                                L9: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_Ext-4CNOS-R_Ext-4CNOS-R
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_Ext-5R!H-R
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_4CNOS->C
                                L9: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_4CNOS->C_Sp-5R!H-4C
                                    L10: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_4CNOS->C_Sp-5R!H-4C_5R!H->C
                                    L10: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_4CNOS->C_Sp-5R!H-4C_N-5R!H->C
                                L9: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_4CNOS->C_N-Sp-5R!H-4C
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C
                                L9: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_5R!H-u0
                                    L10: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_5R!H-u0_5R!H->C
                                    L10: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_5R!H-u0_N-5R!H->C
                                L9: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_Ext-4CNOS-R_N-Sp-5R!H=4CCNNOOSS_N-4CNOS->C_N-5R!H-u0
                    L6: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_4CNOS->C
                    L6: Root_N-4R->H_4CNOS-u1_1R!H->O_2R!H->C_N-4CNOS->C
                L5: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C
                    L6: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_4CNOS->O
                        L7: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_4CNOS->O_Ext-4O-R
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_4CNOS->O_Ext-4O-R_2NOS->N
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_4CNOS->O_Ext-4O-R_N-2NOS->N
                    L6: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O
                        L7: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_4CN->C
                        L7: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_Ext-4N-R
                                L9: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_Ext-4N-R_5R!H->N
                                L9: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_Ext-4N-R_N-5R!H->N
                                    L10: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_Ext-4N-R_N-5R!H->N_5BrCClFIOPSSi->C
                                    L10: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_Ext-4N-R_N-5R!H->N_N-5BrCClFIOPSSi->C
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_2NOS->N
                            L8: Root_N-4R->H_4CNOS-u1_1R!H->O_N-2R!H->C_N-4CNOS->O_N-4CN->C_N-2NOS->N
            L4: Root_N-4R->H_4CNOS-u1_N-1R!H->O
                L5: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O
                    L6: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_Sp-2R!H-1CNS
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_Sp-2R!H-1CNS_2R!H->N
                                    L10: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_Sp-2R!H-1CNS_2R!H->N_2N-u1
                                    L10: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_Sp-2R!H-1CNS_2R!H->N_N-2N-u1
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_Sp-2R!H-1CNS_N-2R!H->N
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_N-Sp-2R!H-1CNS
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_N-Sp-2R!H-1CNS_1CNS->C
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_5R!H-u0_N-Sp-2R!H-1CNS_N-1CNS->C
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_N-5R!H-u0
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_N-5R!H-u0_Sp-2R!H-1CNS
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_N-5R!H-u0_N-Sp-2R!H-1CNS
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_N-5R!H-u0_N-Sp-2R!H-1CNS_1CNS->C
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Ext-4O-R_N-5R!H-u0_N-Sp-2R!H-1CNS_N-1CNS->C
                    L6: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_1CNS->C
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_1CNS->C_2R!H->C
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_1CNS->C_N-2R!H->C
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_2R!H->N
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_2R!H->N_2N-u1
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_2R!H->N_N-2N-u1
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->N
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->N_2CO->C
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->N_N-2CO->C
                    L6: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_N-Sp-2R!H-1CNS
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_N-Sp-2R!H-1CNS_1CNS->C
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_N-Sp-2R!H-1CNS_N-1CNS->C
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_N-Sp-2R!H-1CNS_N-1CNS->C_2R!H->C
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_4CNOS->O_N-Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C
                L5: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O
                    L6: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_Sp-5R!H#4CCCNNNSSS
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_2R!H->S
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_5R!H->O
                                    L10: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_5R!H->O_1CNS->C
                                    L10: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_5R!H->O_N-1CNS->C
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O
                                    L10: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS
                                        L11: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_Ext-4CNS-R
                                            L12: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_Ext-4CNS-R_Ext-4CNS-R
                                        L11: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C
                                            L12: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_1CNS->C_Ext-5CS-R
                                        L11: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_Sp-5CS-4CCNSS_N-1CNS->C
                                    L10: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_Ext-4CNS-R_N-Sp-5R!H#4CCCNNNSSS_N-2R!H->S_N-5R!H->O_N-Sp-5CS-4CCNSS
                    L6: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_Sp-2R!H-1C
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_Sp-2R!H-1C_2R!H->C
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_Sp-2R!H-1C_N-2R!H->C
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_1CNS->C_N-Sp-2R!H-1C
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_2R!H->C
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_2R!H->C_Sp-2C-1N
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_2R!H->C_N-Sp-2C-1N
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_N-2R!H->C
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_N-2R!H->C_2NO-u1
                                    L10: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_N-2R!H->C_2NO-u1_2NO->N
                                    L10: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_N-2R!H->C_2NO-u1_N-2NO->N
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_4CNS->C_N-1CNS->C_N-2R!H->C_N-2NO-u1
                    L6: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_Sp-2R!H-1CNS
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_Sp-2R!H-1CNS_2R!H->N
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_Sp-2R!H-1CNS_2R!H->N_2N-u1
                                L9: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_Sp-2R!H-1CNS_2R!H->N_N-2N-u1
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_Sp-2R!H-1CNS_N-2R!H->N
                        L7: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_N-Sp-2R!H-1CNS
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_N-Sp-2R!H-1CNS_1CNS->C
                            L8: Root_N-4R->H_4CNOS-u1_N-1R!H->O_N-4CNOS->O_N-4CNS->C_N-Sp-2R!H-1CNS_N-1CNS->C
        L3: Root_N-4R->H_N-4CNOS-u1
            L4: Root_N-4R->H_N-4CNOS-u1_1R!H->O
                L5: Root_N-4R->H_N-4CNOS-u1_1R!H->O_4CNOS->C
                L5: Root_N-4R->H_N-4CNOS-u1_1R!H->O_N-4CNOS->C
                    L6: Root_N-4R->H_N-4CNOS-u1_1R!H->O_N-4CNOS->C_2R!H->C
                    L6: Root_N-4R->H_N-4CNOS-u1_1R!H->O_N-4CNOS->C_N-2R!H->C
            L4: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O
                L5: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS
                    L6: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_1CNS->C
                        L7: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_1CNS->C_2R!H->C
                        L7: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_1CNS->C_N-2R!H->C
                    L6: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C
                        L7: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_2R!H->C
                        L7: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C
                            L8: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C_2NO-u1
                                L9: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C_2NO-u1_2NO->N
                                L9: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C_2NO-u1_N-2NO->N
                            L8: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C_N-2NO-u1
                L5: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_N-Sp-2R!H-1CNS
                    L6: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_N-Sp-2R!H-1CNS_1CNS->C
                    L6: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_N-Sp-2R!H-1CNS_N-1CNS->C
                        L7: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_N-Sp-2R!H-1CNS_N-1CNS->C_2R!H->C
                        L7: Root_N-4R->H_N-4CNOS-u1_N-1R!H->O_N-Sp-2R!H-1CNS_N-1CNS->C_N-2R!H->C
"""
)

forbidden(
    label = "O2d",
    group = 
"""
1 *2 O u0 {2,D}
2 *3 O u0 {1,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "OS_XH_birad_singlet",
    group = 
"""
1 *3 [O,S] u0 p3 {2,[S,D,T]}
2 *2 R!H   ux {1,[S,D,T]} {3,S}
3 *4 H     u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "O_Srad",
    group = 
"""
1 *2 [O,S] u0 p2 {2,S} {3,S}
2 *3 [O,S] u1 p2 {1,S}
3 *4 H     u0 {1,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_N_birad_singlet",
    group = 
"""
1 *3 N   u0 p2 {2,[S,D]}
2 *2 R!H ux {1,[S,D]} {3,S}
3 *4 H   u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_birad_singlet",
    group = 
"""
1 *3 [C,Si] u0 p1 {2,[S,D,T]}
2 *2 R!H    ux {1,[S,D,T]} {3,S}
3 *4 H      u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_quadrad_singlet",
    group = 
"""
1 *3 [C,Si] u0 p2 {2,[S,D,T]}
2 *2 R!H    ux {1,[S,D,T]} {3,S}
3 *4 H      u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)


forbidden(
    label = "Ar_metastable_biradical",
    group =
"""
1 *1 Ar u2 p3 c0
""",
    shortDesc = """Metastable argon is outside this family's scope, and the covalent argon it would build has no atom type""",
    longDesc =
"""
OUT OF SCOPE, AND ITS PRODUCTS ARE NOT REPRESENTABLE.
`Ar u2 p3 c0` is metastable argon, Ar(4s 3P2), entered in
input/thermo/libraries/PlasmaExcitedNeutralThermo.py. It is a BIRADICAL, and the atom
type that perceives it, Ar0e, is declared generic under R/R!H in RMG-Py
(rmgpy/molecule/atomtype.py) -- correctly, which is the point of this entry. Argon
brings 8 valence electrons, so in a MOLECULE 8 - c = bonds + 2p + u (the 8 is argon's
valence count, not a universal constant), and a bond-free neutral argon at p3 c0 has u2 and no
choice about it, and Ar0e perceives exactly one molecule: this one. A generic site at
u2 is RIGHT to match it. What is missing is this family's own statement of scope,
which is what this entry supplies. Abstracting a beta hydrogen onto a noble gas is not chemistry this family's
tree or its rate rules describe; the abstracting radical is written as a
generic, which is what lets argon in.

The consequence without this entry is not a wrong rate, it is a dead job. Measured over
all 140 loadable families with 50 ordinary gas-phase partners
(docs/argon-metastable-thermo/all_family_reachability_probe.py and
silent_number_probe.py): this family generates RH. + Ar(3P2) <=> [ArH] + R against 7 of the 50 partners, and every one of those products
raises

    AtomTypeError: Unable to determine atom type for atom Ar, which has 2 single bonds,
                   ..., 3 lone pairs, and +0 charge.

inside estimate_radical_thermo_via_hbi. The reason is structural rather than incidental:
RMG refuses `1 Ar u0 p3 c0 {2,S}` as an invalid valency, so a NEUTRAL argon carrying a
covalent bond is necessarily a radical; a radical's thermo goes through HBI, which
saturates the radical site; and saturating a one-bond argon gives a two-bond argon that
has no atom type at all. So it can never be a silently wrong number -- but it does
terminate mechanism generation, from inside make_new_species, before any kinetics gate
is reached. A quarantine manifest cannot help for that reason; measured in
docs/argon-metastable-thermo/job_level_crash_probe.py.

WHY THE LABEL IS LOAD-BEARING. ForbiddenStructures.is_molecule_forbidden honours atom
labels (rmgpy/data/base.py), so an UNLABELLED `1 Ar u2 p3 c0` group silently matches
nothing during generation -- the molecule's argon is labelled *1 by then and cannot
map to an unlabelled group atom. Measured both ways: unlabelled leaves all reactions in
place, *1 removes them.

WHAT IT DOES NOT TOUCH. This group matches metastable argon and nothing else. Measured
controls, unchanged with it in place: [CH3] + C[CH2] and [OH] + C[CH2] both still generate. It also leaves
Plasma_Electron_Impact_Ionization's Ar(3P2) => Ar+ channel alone, which is the one
reaction this species is supposed to have.

THIS IS THE FIX, AT THE LAYER THE ERROR IS ON. Not a workaround held open pending an
engine change: the argon atom types are correct as they stand (owner's ruling,
2026-09-21; measured in docs/argon-metastable-thermo/atomtype_u_determined_probe.py).
atomtype.py's note that Ar0e "answers for five (u, p, c) triples" describes GROUP
patterns, where ux can be hand-written and no valency check applies -- families generate
molecules. An earlier draft of this block read that comment at the molecule layer and
named the engine as the root cause; that was wrong and is retracted here.

NOT COMPLETE, THOUGH. This entry closes the five families measured to reach the species
today; it cannot close a family nobody has generated against yet. A sixth would be a
family declaring a u2 site broader than the chemistry it intends and shipping without
saying so -- the same defect as this one, in that family, and fixed the same way. It
would not be an engine defect returning. See "THIS IS NOT AN INERT ISLAND" in
PlasmaExcitedNeutralThermo.py's entry for the full reach figure.
""",
)
