#!/usr/bin/env python
# encoding: utf-8

name = "CO_Disproportionation/groups"
shortDesc = ""
longDesc = """
This family describes reactions of the sort:
Y_rad + [CH]=O <=> Y_H + [C-]#[O+]

atom labels:

  R_rad   +        [CH]=O        <=>     RH     +    [C-]#[O+]

R_rad(*1) + H(*4)C_rad(*3)=O(*2) <=> R(*1)H(*4) + [C-](*3)#[O+](*2)
"""

template(reactants=["Root"], products=["Y_H", "CO_CS"], ownReverse=False)

reverse = "CO_Addition"
reversible = True

autoGenerated = True
reactantNum = 2
productNum = 2

recipe(actions=[
    ['FORM_BOND', '*1', 1, '*4'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['LOSE_PAIR', '*2', '1'],
    ['GAIN_PAIR', '*3', '1'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['LOSE_RADICAL', '*1', '1'],
    ['LOSE_RADICAL', '*3', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *3 C       u1         p0 c0 {2,S} {3,D}
2 *4 H       u0         p0 c0 {1,S}
3 *2 [O,S2d] u0         p2 c0 {1,D}
4 *1 R       u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_4R->N",
    group = 
"""
1 *3 C u1         p0 c0 r0 {2,S} {3,D}
2 *4 H u0         p0 c0 r0 {1,S}
3 *2 O u0         p2 c0 r0 {1,D}
4 *1 N u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_N-4R->N",
    group = 
"""
1 *3 C                        u1         p0 c0 {2,S} {3,D}
2 *4 H                        u0         p0 c0 {1,S}
3 *2 O                        u0         p2 c0 {1,D}
4 *1 [P,Br,Cl,C,O,Si,H,S,F,I] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_N-4R->N_4BrCClFHIOPSSi->H",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p0 c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 H u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 H     u0         p0 c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 [C,O] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 H     u0         p0 c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 [C,O] u[1,2,3,4] {5,[S,D,T,B,Q]}
5    R!H   ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 H     u0         p0 c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 [C,O] u[1,2,3,4] {5,[S,D,T,B,Q]}
5    C     ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Ext-4CO-R",
    group = 
"""
1 *3 C     u1         p0 c0 r0 {2,S} {3,D}
2 *4 H     u0         p0 c0 r0 {1,S}
3 *2 O     u0         p2 c0 r0 {1,D}
4 *1 [C,O] u[1,2,3,4] r0 {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
5    C     u0         {4,[S,D,T,B,Q]}
6    R!H   ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 H     u0         p0 c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 [C,O] u[1,2,3,4] {5,S}
5    C     ux         {4,S}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO_4CO->C",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p0 c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4] {5,S}
5    C ux         {4,S}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO_4CO->C_Ext-5C-R",
    group = 
"""
1 *3 C   u1         p0 c0 {2,S} {3,D}
2 *4 H   u0         p0 c0 {1,S}
3 *2 O   u0         p2 c0 {1,D}
4 *1 C   u[1,2,3,4] {5,S}
5    C   ux         {4,S} {6,[S,D,T,B,Q]}
6    R!H ux         {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO_N-4CO->C",
    group = 
"""
1 *3 C u1 p0 c0 r0 {2,S} {3,D}
2 *4 H u0 p0 c0 r0 {1,S}
3 *2 O u0 p2 c0 r0 {1,D}
4 *1 O u1 r0 {5,S}
5    C u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_N-Sp-5C-4CO",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 H     u0         p0 c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 [C,O] u[1,2,3,4] {5,D}
5    C     ux         {4,D}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C",
    group = 
"""
1 *3 C                      u1         p0 c0 {2,S} {3,D}
2 *4 H                      u0         p0 c0 {1,S}
3 *2 O                      u0         p2 c0 {1,D}
4 *1 [C,O]                  u[1,2,3,4] {5,[S,D,T,B,Q]}
5    [P,Br,Cl,O,Si,S,N,F,I] ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 H     u0         p0 c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 [C,O] u[1,2,3,4] {5,[S,D,T,B,Q]}
5    O     ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_4CO->C",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p0 c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4] {5,[S,D,T,B,Q]}
5    O u0         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_4CO->C_Sp-5O-4C",
    group = 
"""
1 *3 C u1         p0 c0 r0 {2,S} {3,D}
2 *4 H u0         p0 c0 r0 {1,S}
3 *2 O u0         p2 c0 r0 {1,D}
4 *1 C u[1,2,3,4] r0 {5,S}
5    O u0         {4,S}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_4CO->C_N-Sp-5O-4C",
    group = 
"""
1 *3 C u1         p0 c0 r0 {2,S} {3,D}
2 *4 H u0         p0 c0 r0 {1,S}
3 *2 O u0         p2 c0 r0 {1,D}
4 *1 C u[1,2,3,4] r0 {5,D}
5    O u0         {4,D}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_N-4CO->C",
    group = 
"""
1 *3 C u1 p0 c0 {2,S} {3,D}
2 *4 H u0 p0 c0 {1,S}
3 *2 O u0 p2 c0 {1,D}
4 *1 O u1 {5,[S,D,T,B,Q]}
5    O ux r0 {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_N-5BrClFINOPSSi->O",
    group = 
"""
1 *3 C     u1         p0 c0 r0 {2,S} {3,D}
2 *4 H     u0         p0 c0 r0 {1,S}
3 *2 O     u0         p2 c0 r0 {1,D}
4 *1 [C,O] u[1,2,3,4] r0 {5,[S,D,T,B,Q]}
5    N     ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_4CO->C",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p0 c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_N-4R->N_N-4BrCClFHIOPSSi->H_N-4CO->C",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p0 c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 O u[1,2,3,4]
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_4R->N
    L2: Root_N-4R->N
        L3: Root_N-4R->N_4BrCClFHIOPSSi->H
        L3: Root_N-4R->N_N-4BrCClFHIOPSSi->H
            L4: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R
                L5: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C
                    L6: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Ext-4CO-R
                    L6: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO
                        L7: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO_4CO->C
                            L8: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO_4CO->C_Ext-5C-R
                        L7: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_Sp-5C-4CO_N-4CO->C
                    L6: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_5R!H->C_N-Sp-5C-4CO
                L5: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C
                    L6: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O
                        L7: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_4CO->C
                            L8: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_4CO->C_Sp-5O-4C
                            L8: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_4CO->C_N-Sp-5O-4C
                        L7: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_5BrClFINOPSSi->O_N-4CO->C
                    L6: Root_N-4R->N_N-4BrCClFHIOPSSi->H_Ext-4CO-R_N-5R!H->C_N-5BrClFINOPSSi->O
            L4: Root_N-4R->N_N-4BrCClFHIOPSSi->H_4CO->C
            L4: Root_N-4R->N_N-4BrCClFHIOPSSi->H_N-4CO->C
"""
)

forbidden(
    label = "O2d",
    group = 
"""
1 *2 O u0 {2,D}
2 *3 O u0 {1,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "OS_XH_birad_singlet",
    group = 
"""
1 *3 [O,S] u0 p3 {2,[S,D,T]}
2 *2 R!H   ux {1,[S,D,T]} {3,S}
3 *4 H     u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "O_Orad",
    group = 
"""
1 *2 O u0 {2,S} {3,S}
2 *3 O u1 {1,S}
3 *4 H u0 {1,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_N_birad_singlet",
    group = 
"""
1 *3 N   u0 p2 {2,[S,D]}
2 *2 R!H ux {1,[S,D]} {3,S}
3 *4 H   u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_birad_singlet",
    group = 
"""
1 *3 [C,Si] u0 p1 {2,[S,D,T]}
2 *2 R!H    ux {1,[S,D,T]} {3,S}
3 *4 H      u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_quadrad_singlet",
    group = 
"""
1 *3 [C,Si] u0 p2 {2,[S,D,T]}
2 *2 R!H    ux {1,[S,D,T]} {3,S}
3 *4 H      u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)


forbidden(
    label = "Ar_metastable_biradical",
    group =
"""
1 *1 Ar u2 p3 c0
""",
    shortDesc = """Metastable argon is outside this family's scope, and the covalent argon it would build has no atom type""",
    longDesc =
"""
OUT OF SCOPE, AND ITS PRODUCTS ARE NOT REPRESENTABLE.
`Ar u2 p3 c0` is metastable argon, Ar(4s 3P2), entered in
input/thermo/libraries/PlasmaExcitedNeutralThermo.py. It is a BIRADICAL, and the atom
type that perceives it, Ar0e, is declared generic under R/R!H in RMG-Py
(rmgpy/molecule/atomtype.py) -- correctly, which is the point of this entry. Argon
brings 8 valence electrons, so in a MOLECULE 8 - c = bonds + 2p + u (the 8 is argon's
valence count, not a universal constant), and a bond-free neutral argon at p3 c0 has u2 and no
choice about it, and Ar0e perceives exactly one molecule: this one. A generic site at
u2 is RIGHT to match it. What is missing is this family's own statement of scope,
which is what this entry supplies. Abstracting the formyl hydrogen onto a noble gas is not chemistry this
family's tree or its rate rules describe; the abstracting radical is written as
a generic, which is what lets argon in.

The consequence without this entry is not a wrong rate, it is a dead job. Measured over
all 140 loadable families with 50 ordinary gas-phase partners
(docs/argon-metastable-thermo/all_family_reachability_probe.py and
silent_number_probe.py): this family generates HCO + Ar(3P2) <=> [ArH] + CO, and every one of those products
raises

    AtomTypeError: Unable to determine atom type for atom Ar, which has 2 single bonds,
                   ..., 3 lone pairs, and +0 charge.

inside estimate_radical_thermo_via_hbi. The reason is structural rather than incidental:
RMG refuses `1 Ar u0 p3 c0 {2,S}` as an invalid valency, so a NEUTRAL argon carrying a
covalent bond is necessarily a radical; a radical's thermo goes through HBI, which
saturates the radical site; and saturating a one-bond argon gives a two-bond argon that
has no atom type at all. So it can never be a silently wrong number -- but it does
terminate mechanism generation, from inside make_new_species, before any kinetics gate
is reached. A quarantine manifest cannot help for that reason; measured in
docs/argon-metastable-thermo/job_level_crash_probe.py.

WHY THE LABEL IS LOAD-BEARING. ForbiddenStructures.is_molecule_forbidden honours atom
labels (rmgpy/data/base.py), so an UNLABELLED `1 Ar u2 p3 c0` group silently matches
nothing during generation -- the molecule's argon is labelled *1 by then and cannot
map to an unlabelled group atom. Measured both ways: unlabelled leaves all reactions in
place, *1 removes them.

WHAT IT DOES NOT TOUCH. This group matches metastable argon and nothing else. Measured
controls, unchanged with it in place: [H] + [CH]=O and [CH3] + [CH]=O both still generate. It also leaves
Plasma_Electron_Impact_Ionization's Ar(3P2) => Ar+ channel alone, which is the one
reaction this species is supposed to have.

THIS IS THE FIX, AT THE LAYER THE ERROR IS ON. Not a workaround held open pending an
engine change: the argon atom types are correct as they stand (owner's ruling,
2026-09-21; measured in docs/argon-metastable-thermo/atomtype_u_determined_probe.py).
atomtype.py's note that Ar0e "answers for five (u, p, c) triples" describes GROUP
patterns, where ux can be hand-written and no valency check applies -- families generate
molecules. An earlier draft of this block read that comment at the molecule layer and
named the engine as the root cause; that was wrong and is retracted here.

NOT COMPLETE, THOUGH. This entry closes the five families measured to reach the species
today; it cannot close a family nobody has generated against yet. A sixth would be a
family declaring a u2 site broader than the chemistry it intends and shipping without
saying so -- the same defect as this one, in that family, and fixed the same way. It
would not be an engine defect returning. See "THIS IS NOT AN INERT ISLAND" in
PlasmaExcitedNeutralThermo.py's entry for the full reach figure.
""",
)
