#!/usr/bin/env python
# encoding: utf-8

name = "Disproportionation-Y/groups"
shortDesc = ""
longDesc = """
If a birad, reaction site *1 needs to be a triplet.
If a birad, reaction site *3 needs to be a triplet.
If a tri-rad or quad-rad, reaction site *1 and *3 can be anything but singlet.
"""

template(reactants=["Root"], products=["Y_H", "X_R"], ownReverse=False)

reverse = "Molecular_Addition"
reversible = True

reactantNum = 2

productNum = 2

autoGenerated = True

recipe(actions=[
    ['FORM_BOND', '*1', 1, '*4'],
    ['BREAK_BOND', '*2', 1, '*4'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['LOSE_RADICAL', '*1', '1'],
    ['LOSE_RADICAL', '*3', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *2 R!H             u0         {2,[S,D,B]} {3,S}
2 *3 R!H             u[1,2]     {1,[S,D,B]}
3 *4 [F1s,Cl1s,Br1s] u0         {1,S}
4 *1 R               u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_4R->F",
    group = 
"""
1 *2 C   u0         {2,S} {3,S}
2 *3 R!H u[1,2]     {1,S}
3 *4 F1s u0         {1,S}
4 *1 F   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_4R->F_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0         {2,S} {3,S} {5,[S,D,T,B,Q]}
2 *3 R!H u[1,2]     {1,S}
3 *4 F1s u0         {1,S}
4 *1 F   u[1,2,3,4]
5    R!H ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_N-4R->F",
    group = 
"""
1 *2 C                        u0         {2,[S,D,B]} {3,S}
2 *3 R!H                      u[1,2]     {1,[S,D,B]}
3 *4 [F1s,Cl1s,Br1s]          u0         {1,S}
4 *1 [C,N,P,H,Si,I,Br,Cl,O,S] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H",
    group = 
"""
1 *2 C               u0         {2,[S,D,B]} {3,S}
2 *3 R!H             u[1,2]     {1,[S,D,B]}
3 *4 [F1s,Cl1s,Br1s] u0         {1,S}
4 *1 H               u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s",
    group = 
"""
1 *2 C    u0         {2,[S,D,B]} {3,S}
2 *3 C    u[1,2]     {1,[S,D,B]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R",
    group = 
"""
1 *2 C    u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,[S,D,B]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    R!H  ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl",
    group = 
"""
1 *2 C    u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,[S,D,B]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-1R!H-R",
    group = 
"""
1 *2 C    u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,[S,D,B]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {1,[S,D,T,B,Q]}
6    Cl   ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-1R!H-R_Ext-2R!H-R",
    group = 
"""
1 *2 C    u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,[S,D,B]} {7,[S,D,T,B,Q]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {1,[S,D,T,B,Q]}
6    Cl   ux         {1,[S,D,T,B,Q]}
7    R!H  ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-1R!H-R_Ext-2R!H-R_Ext-2R!H-R",
    group = 
"""
1 *2 C    u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,[S,D,B]} {7,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {1,[S,D,T,B,Q]}
6    Cl   ux         {1,[S,D,T,B,Q]}
7    R!H  ux         {2,[S,D,T,B,Q]}
8    R!H  ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-2R!H-R",
    group = 
"""
1 *2 C    u0         {2,[S,D,B]} {3,S} {5,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,[S,D,B]} {6,[S,D,T,B,Q]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {1,[S,D,T,B,Q]}
6    R!H  ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-2R!H-R_Ext-2R!H-R",
    group = 
"""
1 *2 C    u0 r0 {2,[S,D,B]} {3,S} {5,S}
2 *3 C    u1 r0 {1,[S,D,B]} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
3 *4 Cl1s u0 r0 {1,S}
4 *1 H    u1 r0
5    Cl   u0 r0 {1,S}
6    R!H  ux {2,[S,D,T,B,Q]}
7    R!H  ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-2R!H-R_Sp-2R!H-1R!H",
    group = 
"""
1 *2 C    u0         {2,S} {3,S} {5,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,S} {6,[S,D,T,B,Q]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {1,[S,D,T,B,Q]}
6    Cl   ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-2R!H-R_N-Sp-2R!H-1R!H",
    group = 
"""
1 *2 C    u0         {2,D} {3,S} {5,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,D} {6,[S,D,T,B,Q]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {1,[S,D,T,B,Q]}
6    Cl   ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Sp-2R!H-1R!H",
    group = 
"""
1 *2 C    u0         {2,S} {3,S} {5,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,S}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_N-Sp-2R!H-1R!H",
    group = 
"""
1 *2 C    u0         {2,D} {3,S} {5,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,D}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_N-5R!H->Cl",
    group = 
"""
1 *2 C                     u0 r0 {2,[S,D,B]} {3,S} {5,S}
2 *3 C                     u1 r0 {1,[S,D,B]}
3 *4 Cl1s                  u0 r0 {1,S}
4 *1 H                     u1 r0
5    [C,N,P,Si,F,I,Br,O,S] u0 r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-2R!H-R",
    group = 
"""
1 *2 C    u0         {2,[S,D,B]} {3,S}
2 *3 C    u[1,2]     {1,[S,D,B]} {5,[S,D,T,B,Q]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    R!H  ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Ext-2R!H-R",
    group = 
"""
1 *2 C    u0 r0 {2,[S,D,B]} {3,S}
2 *3 C    u1 r0 {1,[S,D,B]} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
3 *4 Cl1s u0 r0 {1,S}
4 *1 H    u1 r0
5    R!H  ux {2,[S,D,T,B,Q]}
6    R!H  ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H",
    group = 
"""
1 *2 C    u0         {2,S} {3,S}
2 *3 C    u[1,2]     {1,S} {5,[S,D,T,B,Q]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_N-Sp-2R!H-1R!H",
    group = 
"""
1 *2 C    u0         {2,D} {3,S}
2 *3 C    u[1,2]     {1,D} {5,[S,D,T,B,Q]}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
5    Cl   ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H",
    group = 
"""
1 *2 C    u0         {2,S} {3,S}
2 *3 C    u[1,2]     {1,S}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_N-Sp-2R!H-1R!H",
    group = 
"""
1 *2 C    u0         {2,D} {3,S}
2 *3 C    u[1,2]     {1,D}
3 *4 Cl1s u0         {1,S}
4 *1 H    u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s",
    group = 
"""
1 *2 C          u0         {2,[S,D,B]} {3,S}
2 *3 R!H        u[1,2]     {1,[S,D,B]}
3 *4 [F1s,Br1s] u0         {1,S}
4 *1 H          u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R",
    group = 
"""
1 *2 C          u0         {2,[S,D,B]} {3,S}
2 *3 C          u[1,2]     {1,[S,D,B]} {5,[S,D,T,B,Q]}
3 *4 [F1s,Br1s] u0         {1,S}
4 *1 H          u[1,2,3,4]
5    R!H        ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H",
    group = 
"""
1 *2 C          u0         {2,S} {3,S}
2 *3 C          u[1,2]     {1,S} {5,[S,D,T,B,Q]}
3 *4 [F1s,Br1s] u0         {1,S}
4 *1 H          u[1,2,3,4]
5    R!H        ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R",
    group = 
"""
1 *2 C          u0         {2,S} {3,S} {6,[S,D,T,B,Q]}
2 *3 C          u[1,2]     {1,S} {5,[S,D,T,B,Q]}
3 *4 [F1s,Br1s] u0         {1,S}
4 *1 H          u[1,2,3,4]
5    R!H        ux         {2,[S,D,T,B,Q]}
6    R!H        ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 28,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R_3Br1sF1s->F1s",
    group = 
"""
1 *2 C   u0         {2,S} {3,S} {6,[S,D,T,B,Q]}
2 *3 C   u[1,2]     {1,S} {5,[S,D,T,B,Q]}
3 *4 F1s u0         {1,S}
4 *1 H   u[1,2,3,4]
5    R!H ux         {2,[S,D,T,B,Q]}
6    R!H ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 29,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R_3Br1sF1s->F1s_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 {2,S} {3,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
2 *3 C   u1 {1,S} {5,[S,D,T,B,Q]}
3 *4 F1s u0 {1,S}
4 *1 H   u1
5    R!H ux {2,[S,D,T,B,Q]}
6    R!H ux {1,[S,D,T,B,Q]}
7    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 30,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R_3Br1sF1s->F1s_Ext-1R!H-R_Ext-2R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
2 *3 C   u1 r0 {1,S} {5,[S,D,T,B,Q]} {8,[S,D,T,B,Q]}
3 *4 F1s u0 r0 {1,S}
4 *1 H   u1 r0
5    R!H ux {2,[S,D,T,B,Q]}
6    R!H ux {1,[S,D,T,B,Q]}
7    R!H ux {1,[S,D,T,B,Q]}
8    R!H ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 31,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R_3Br1sF1s->F1s_Ext-2R!H-R",
    group = 
"""
1 *2 C   u0         {2,S} {3,S} {6,[S,D,T,B,Q]}
2 *3 C   u[1,2]     {1,S} {5,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
3 *4 F1s u0         {1,S}
4 *1 H   u[1,2,3,4]
5    R!H ux         {2,[S,D,T,B,Q]}
6    F   ux         {1,[S,D,T,B,Q]}
7    R!H ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 32,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R_N-3Br1sF1s->F1s",
    group = 
"""
1 *2 C    u0 r0 {2,S} {3,S} {6,S}
2 *3 C    u1 r0 {1,S} {5,S}
3 *4 Br1s u0 r0 {1,S}
4 *1 H    u1 r0
5    F    u0 r0 {2,S}
6    F    u0 r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 33,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-2R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S}
2 *3 C   u1 r0 {1,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
3 *4 F1s u0 r0 {1,S}
4 *1 H   u1 r0
5    R!H ux {2,[S,D,T,B,Q]}
6    R!H ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 34,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_N-Sp-2R!H-1R!H",
    group = 
"""
1 *2 C   u0         {2,D} {3,S}
2 *3 C   u[1,2]     {1,D} {5,[S,D,T,B,Q]}
3 *4 F1s u0         {1,S}
4 *1 H   u[1,2,3,4]
5    R!H ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 35,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_N-Sp-2R!H-1R!H_5R!H->C",
    group = 
"""
1 *2 C   u0         {2,D} {3,S}
2 *3 C   u[1,2]     {1,D} {5,[S,D,T,B,Q]}
3 *4 F1s u0         {1,S}
4 *1 H   u[1,2,3,4]
5    C   ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 36,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_N-Sp-2R!H-1R!H_N-5R!H->C",
    group = 
"""
1 *2 C   u0 {2,D} {3,S}
2 *3 C   u1 {1,D} {5,S}
3 *4 F1s u0 {1,S}
4 *1 H   u1
5    F   u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 37,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_N-Sp-2R!H-1R!H_N-5R!H->C_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,D} {3,S} {6,[S,D,T,B,Q]}
2 *3 C   u1 r0 {1,D} {5,S}
3 *4 F1s u0 r0 {1,S}
4 *1 H   u1 r0
5    F   u0 r0 {2,S}
6    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 38,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H",
    group = 
"""
1 *2 C   u0 {2,S} {3,S}
2 *3 R!H u1 {1,S}
3 *4 F1s u0 {1,S}
4 *1 H   u1
""",
    kinetics = None,
)

entry(
    index = 39,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H_2R!H->C",
    group = 
"""
1 *2 C   u0 {2,S} {3,S}
2 *3 C   u1 {1,S}
3 *4 F1s u0 {1,S}
4 *1 H   u1
""",
    kinetics = None,
)

entry(
    index = 40,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H_2R!H->C_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 {2,S} {3,S} {5,[S,D,T,B,Q]}
2 *3 C   u1 {1,S}
3 *4 F1s u0 {1,S}
4 *1 H   u1
5    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 41,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H_2R!H->C_Ext-1R!H-R_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S} {5,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
2 *3 C   u1 r0 {1,S}
3 *4 F1s u0 r0 {1,S}
4 *1 H   u1 r0
5    R!H ux {1,[S,D,T,B,Q]}
6    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 42,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H_N-2R!H->C",
    group = 
"""
1 *2 C   u0 r0 {2,S} {3,S}
2 *3 O   u1 r0 {1,S}
3 *4 F1s u0 r0 {1,S}
4 *1 H   u1 r0
""",
    kinetics = None,
)

entry(
    index = 43,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_N-Sp-2R!H-1R!H",
    group = 
"""
1 *2 C   u0         {2,D} {3,S}
2 *3 C   u[1,2]     {1,D}
3 *4 F1s u0         {1,S}
4 *1 H   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 44,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_N-Sp-2R!H-1R!H_Ext-1R!H-R",
    group = 
"""
1 *2 C   u0         {2,D} {3,S} {5,S}
2 *3 C   u[1,2]     {1,D}
3 *4 F1s u0         {1,S}
4 *1 H   u[1,2,3,4]
5    R!H u0         {1,S}
""",
    kinetics = None,
)

entry(
    index = 45,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_N-Sp-2R!H-1R!H_Ext-1R!H-R_5R!H->C",
    group = 
"""
1 *2 C   u0         {2,D} {3,S} {5,S}
2 *3 C   u[1,2]     {1,D}
3 *4 F1s u0         {1,S}
4 *1 H   u[1,2,3,4]
5    C   u0         r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 46,
    label = "Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_N-Sp-2R!H-1R!H_Ext-1R!H-R_N-5R!H->C",
    group = 
"""
1 *2 C   u0 r0 {2,D} {3,S} {5,S}
2 *3 C   u1 r0 {1,D}
3 *4 F1s u0 r0 {1,S}
4 *1 H   u1 r0
5    F   u0 r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 47,
    label = "Root_N-4R->F_N-4BrCClHINOPSSi->H",
    group = 
"""
1 *2 C         u0         {2,[S,D,B]} {3,S}
2 *3 C         u[1,2]     {1,[S,D,B]}
3 *4 Cl1s      u0         {1,S}
4 *1 [Br,O,Cl] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 48,
    label = "Root_N-4R->F_N-4BrCClHINOPSSi->H_Sp-2R!H-1R!H",
    group = 
"""
1 *2 C         u0         {2,S} {3,S}
2 *3 C         u[1,2]     {1,S}
3 *4 Cl1s      u0         {1,S}
4 *1 [Br,O,Cl] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 49,
    label = "Root_N-4R->F_N-4BrCClHINOPSSi->H_Sp-2R!H-1R!H_4BrClO->Br",
    group = 
"""
1 *2 C    u0         {2,S} {3,S}
2 *3 C    u[1,2]     {1,S}
3 *4 Cl1s u0         {1,S}
4 *1 Br   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 50,
    label = "Root_N-4R->F_N-4BrCClHINOPSSi->H_Sp-2R!H-1R!H_N-4BrClO->Br",
    group = 
"""
1 *2 C      u0         {2,S} {3,S}
2 *3 C      u[1,2]     {1,S}
3 *4 Cl1s   u0         {1,S}
4 *1 [O,Cl] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 51,
    label = "Root_N-4R->F_N-4BrCClHINOPSSi->H_N-Sp-2R!H-1R!H",
    group = 
"""
1 *2 C    u0         {2,D} {3,S}
2 *3 C    u[1,2]     {1,D}
3 *4 Cl1s u0         {1,S}
4 *1 O    u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 52,
    label = "Root_N-4R->F_N-4BrCClHINOPSSi->H_N-Sp-2R!H-1R!H_Ext-1R!H-R",
    group = 
"""
1 *2 C    u0         {2,D} {3,S} {5,[S,D,T,B,Q]}
2 *3 C    u[1,2]     {1,D}
3 *4 Cl1s u0         {1,S}
4 *1 O    u[1,2,3,4]
5    R!H  ux         {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 53,
    label = "Root_N-4R->F_N-4BrCClHINOPSSi->H_N-Sp-2R!H-1R!H_Ext-2R!H-R",
    group = 
"""
1 *2 C    u0         {2,D} {3,S}
2 *3 C    u[1,2]     {1,D} {5,[S,D,T,B,Q]}
3 *4 Cl1s u0         {1,S}
4 *1 O    u[1,2,3,4]
5    R!H  ux         {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_4R->F
        L3: Root_4R->F_Ext-1R!H-R
    L2: Root_N-4R->F
        L3: Root_N-4R->F_4BrCClHINOPSSi->H
            L4: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s
                L5: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R
                    L6: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-1R!H-R
                            L8: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-1R!H-R_Ext-2R!H-R
                                L9: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-1R!H-R_Ext-2R!H-R_Ext-2R!H-R
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-2R!H-R
                            L8: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-2R!H-R_Ext-2R!H-R
                            L8: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-2R!H-R_Sp-2R!H-1R!H
                            L8: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Ext-2R!H-R_N-Sp-2R!H-1R!H
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_Sp-2R!H-1R!H
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_5R!H->Cl_N-Sp-2R!H-1R!H
                    L6: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-1R!H-R_N-5R!H->Cl
                L5: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-2R!H-R
                    L6: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Ext-2R!H-R
                    L6: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H
                    L6: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_N-Sp-2R!H-1R!H
                L5: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H
                L5: Root_N-4R->F_4BrCClHINOPSSi->H_3Br1sCl1sF1s->Cl1s_N-Sp-2R!H-1R!H
            L4: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s
                L5: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R
                    L6: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R
                            L8: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R_3Br1sF1s->F1s
                                L9: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R_3Br1sF1s->F1s_Ext-1R!H-R
                                    L10: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R_3Br1sF1s->F1s_Ext-1R!H-R_Ext-2R!H-R
                                L9: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R_3Br1sF1s->F1s_Ext-2R!H-R
                            L8: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-1R!H-R_N-3Br1sF1s->F1s
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_Sp-2R!H-1R!H_Ext-2R!H-R
                    L6: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_N-Sp-2R!H-1R!H
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_N-Sp-2R!H-1R!H_5R!H->C
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_N-Sp-2R!H-1R!H_N-5R!H->C
                            L8: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Ext-2R!H-R_N-Sp-2R!H-1R!H_N-5R!H->C_Ext-1R!H-R
                L5: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H
                    L6: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H_2R!H->C
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H_2R!H->C_Ext-1R!H-R
                            L8: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H_2R!H->C_Ext-1R!H-R_Ext-1R!H-R
                    L6: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_Sp-2R!H-1R!H_N-2R!H->C
                L5: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_N-Sp-2R!H-1R!H
                    L6: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_N-Sp-2R!H-1R!H_Ext-1R!H-R
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_N-Sp-2R!H-1R!H_Ext-1R!H-R_5R!H->C
                        L7: Root_N-4R->F_4BrCClHINOPSSi->H_N-3Br1sCl1sF1s->Cl1s_N-Sp-2R!H-1R!H_Ext-1R!H-R_N-5R!H->C
        L3: Root_N-4R->F_N-4BrCClHINOPSSi->H
            L4: Root_N-4R->F_N-4BrCClHINOPSSi->H_Sp-2R!H-1R!H
                L5: Root_N-4R->F_N-4BrCClHINOPSSi->H_Sp-2R!H-1R!H_4BrClO->Br
                L5: Root_N-4R->F_N-4BrCClHINOPSSi->H_Sp-2R!H-1R!H_N-4BrClO->Br
            L4: Root_N-4R->F_N-4BrCClHINOPSSi->H_N-Sp-2R!H-1R!H
                L5: Root_N-4R->F_N-4BrCClHINOPSSi->H_N-Sp-2R!H-1R!H_Ext-1R!H-R
                L5: Root_N-4R->F_N-4BrCClHINOPSSi->H_N-Sp-2R!H-1R!H_Ext-2R!H-R
"""
)

forbidden(
    label = "C_quintet",
    group = 
"""
1 C u4 p0 c0
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "O2d",
    group = 
"""
1 *2 O u0 {2,D}
2 *3 O u0 {1,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "OS_XH_birad_singlet",
    group = 
"""
1 *3 [O,S]    u0 p3 {2,[S,D,T]}
2 *2 R!H!Val7 ux {1,[S,D,T]} {3,S}
3 *4 Val7     u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "O_Srad",
    group = 
"""
1 *2 [O,S] u0 p2 {2,S} {3,S}
2 *3 [O,S] u1 p2 {1,S}
3 *4 Val7  u0 {1,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_N_birad_singlet",
    group = 
"""
1 *3 N        u0 p2 {2,[S,D]}
2 *2 R!H!Val7 ux {1,[S,D]} {3,S}
3 *4 Val7     u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_birad_singlet",
    group = 
"""
1 *3 [C,Si]   u0 p1 {2,[S,D,T]}
2 *2 R!H!Val7 ux {1,[S,D,T]} {3,S}
3 *4 Val7     u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_quadrad_singlet",
    group = 
"""
1 *3 [C,Si]   u0 p2 {2,[S,D,T]}
2 *2 R!H!Val7 ux {1,[S,D,T]} {3,S}
3 *4 Val7     u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)


forbidden(
    label = "Ar_metastable_biradical",
    group =
"""
1 *1 Ar u2 p3 c0
""",
    shortDesc = """Metastable argon is out of scope for this family.""",
    longDesc = """
METASTABLE ARGON, Ar(4s 3P2), IS OUT OF SCOPE HERE AND ITS PRODUCTS ARE NOT
REPRESENTABLE.
`Ar u2 p3 c0` is metastable argon, entered in
input/thermo/libraries/PlasmaExcitedNeutralThermo.py. It is a BIRADICAL, and the atom
type that perceives it, Ar0e, is declared generic under R/R!H in RMG-Py
(rmgpy/molecule/atomtype.py) -- correctly, which is the point of this entry. Argon
brings 8 valence electrons, so in a MOLECULE 8 - c = bonds + 2p + u (the 8 is argon's
valence count, not a universal constant), and a bond-free neutral argon at p3 c0 has u2 and no
choice about it: Ar0e perceives exactly one molecule, this one. A generic site at
u2 is RIGHT to match it. What is missing is this family's own statement of scope,
which is what this entry supplies. This family is for disproportionation at a beta-heteroatom (Y) site, which is not chemistry a
noble gas participates in.

HOW THIS FAMILY WAS FOUND, AND WHY IT IS NOT A SIXTH GUESS. Not by trying partners. The
shipped template space was decomposed and every family whose per-reactant site admits
`Ar u2 p3 c0` was selected -- see docs/argon-metastable-thermo/template_space_derivation.py,
which re-runs and exits non-zero if any matching family lacks this entry. This family
matches on the forward template, slot 0. The earlier five entries were found by
running 140 families against a hardcoded partner list; that is exhaustive in families and
a SAMPLE in partners, and it missed this one because no suitable partner was in the list.

WHAT IT PREVENTS, MEASURED WITH A PARTNER DERIVED FROM THIS FAMILY'S OWN TEMPLATE
(docs/argon-metastable-thermo/template_witness_probe.py, so the witness does not depend on
anybody's choice of second reactant): a fluorinated radical + Ar* -> [ArF] + alkene, whose [ArF] has no atom type.

WHY THE LABEL IS LOAD-BEARING. ForbiddenStructures.is_molecule_forbidden honours atom
labels (rmgpy/data/base.py), so an UNLABELLED `1 Ar u2 p3 c0` group silently matches
nothing during generation -- the molecule's argon is labelled *1 by then and cannot
map to an unlabelled group atom. This label is not chosen, it is read out of the
matcher's own mapping for this family's template.

THIS IS THE FIX, AT THE LAYER THE ERROR IS ON. Not a workaround held open pending an
engine change: the argon atom types are correct as they stand (owner's ruling,
2026-09-21; measured in docs/argon-metastable-thermo/atomtype_u_determined_probe.py).
atomtype.py's note that Ar0e "answers for five (u, p, c) triples" describes GROUP
patterns, where ux can be hand-written and no valency check applies -- families generate
molecules.

NOT COMPLETE, THOUGH -- but complete against the template space as it ships today. A
family added later whose site admits this structure would reopen the crash, and would be
declaring a u2 site broader than the chemistry it intends: the same defect as this one, in
that family, and fixed the same way. It would not be an engine defect returning. The
derivation above is the check that catches it, and it is re-runnable by whoever adds the
family.
""",
)
