#!/usr/bin/env python
# encoding: utf-8

name = "Li_NO_Substitution/groups"
shortDesc = ""
longDesc = """
If a birad, the reacting site *3 must be a triplet instead of singlet for this reaction family.
"""

template(reactants=["Root"], products=["O-RR_or_RRrad", "YJ"], ownReverse=False)

reverse = "Li_NO_Substitution_reverse"
reversible = True

reactantNum = 2

productNum = 2

autoGenerated = True

recipe(actions=[
    ['LOSE_RADICAL', '*3', 1],
    ['BREAK_BOND', '*1', 1, '*2'],
    ['FORM_BOND', '*1', 1, '*3'],
    ['GAIN_RADICAL', '*2', 1],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *1 [O,N] u0     {2,S} {3,S}
2 *2 R     u[0,1] {1,S}
3    R     u0     {1,S}
4 *3 Li    u1     p0 c0
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_1NO->O",
    group = 
"""
1 *1 O  u0     {2,S} {3,S}
2 *2 R  u[0,1] {1,S}
3    R  u0     {1,S}
4 *3 Li u1     p0 c0
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_1NO->O_Ext-3R-R",
    group = 
"""
1 *1 O  u0     {2,S} {3,S}
2 *2 R  u[0,1] {1,S}
3    C  u0     {1,S} {5,[S,D,T,B,Q]}
4 *3 Li u1     p0 c0
5    C  ux     {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_1NO->O_Ext-3R-R_2R->C",
    group = 
"""
1 *1 O  u0     {2,S} {3,S}
2 *2 C  u[0,1] {1,S}
3    C  u0     {1,S} {5,[S,D,T,B,Q]}
4 *3 Li u1     p0 c0
5    C  ux     {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_1NO->O_Ext-3R-R_2R->C_Ext-5R!H-R",
    group = 
"""
1 *1 O   u0     {2,S} {3,S}
2 *2 C   u[0,1] {1,S}
3    C   u0     {1,S} {5,[S,D,T,B,Q]}
4 *3 Li  u1     p0 c0
5    C   ux     {3,[S,D,T,B,Q]} {6,[S,D,T,B,Q]}
6    R!H ux     {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_1NO->O_Ext-3R-R_N-2R->C",
    group = 
"""
1 *1 O  u0 r0 {2,S} {3,S}
2 *2 H  u0 r0 {1,S}
3    C  u0 r0 {1,S} {5,S}
4 *3 Li u1 p0 c0 r0
5    C  u0 r0 {3,S}
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_1NO->O_3R->C",
    group = 
"""
1 *1 O  u0     {2,S} {3,S}
2 *2 R  u[0,1] {1,S}
3    C  u0     {1,S}
4 *3 Li u1     p0 c0
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_1NO->O_3R->C_Ext-2R-R",
    group = 
"""
1 *1 O   u0 r0 {2,S} {3,S}
2 *2 R   u0 r0 {1,S} {5,[S,D,T,B,Q]}
3    C   u0 r0 {1,S}
4 *3 Li  u1 p0 c0 r0
5    R!H ux {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_1NO->O_3R->C_2R->C",
    group = 
"""
1 *1 O  u0     {2,S} {3,S}
2 *2 C  u[0,1] {1,S}
3    C  u0     {1,S}
4 *3 Li u1     p0 c0
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_1NO->O_3R->C_N-2R->C",
    group = 
"""
1 *1 O  u0     {2,S} {3,S}
2 *2 H  u[0,1] {1,S}
3    C  u0     {1,S}
4 *3 Li u1     p0 c0
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_1NO->O_N-3R->C",
    group = 
"""
1 *1 O  u0     {2,S} {3,S}
2 *2 R  u[0,1] {1,S}
3    H  u0     {1,S}
4 *3 Li u1     p0 c0
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_1NO->O_N-3R->C_2R->C",
    group = 
"""
1 *1 O  u0     {2,S} {3,S}
2 *2 C  u[0,1] {1,S}
3    H  u0     {1,S}
4 *3 Li u1     p0 c0
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_1NO->O_N-3R->C_2R->C_Ext-2C-R",
    group = 
"""
1 *1 O   u0     {2,S} {3,S}
2 *2 C   u[0,1] {1,S} {5,[S,D,T,B,Q]}
3    H   u0     {1,S}
4 *3 Li  u1     p0 c0
5    R!H ux     {2,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_1NO->O_N-3R->C_N-2R->C",
    group = 
"""
1 *1 O  u0     r0 {2,S} {3,S}
2 *2 H  u[0,1] {1,S}
3    H  u0     {1,S}
4 *3 Li u1     p0 c0 r0
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_N-1NO->O",
    group = 
"""
1 *1 N  u0     {2,S} {3,S}
2 *2 R  u[0,1] {1,S}
3    R  u0     {1,S}
4 *3 Li u1     p0 c0
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_N-1NO->O_Ext-2R-R",
    group = 
"""
1 *1 N  u0 {2,S} {3,S}
2 *2 C  u0 {1,S} {5,S}
3    H  u0 {1,S}
4 *3 Li u1 p0 c0
5    C  u0 {2,S}
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_N-1NO->O_Ext-2R-R_Ext-1N-R",
    group = 
"""
1 *1 N   u0 r0 {2,S} {3,S} {6,[S,D,T,B,Q]}
2 *2 C   u0 r0 {1,S} {5,S}
3    H   u0 r0 {1,S}
4 *3 Li  u1 p0 c0 r0
5    C   u0 r0 {2,S}
6    R!H ux {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_N-1NO->O_Ext-1N-R",
    group = 
"""
1 *1 N  u0     {2,S} {3,S} {5,[S,D,T,B,Q]}
2 *2 R  u[0,1] {1,S}
3    R  u0     {1,S}
4 *3 Li u1     p0 c0
5    C  ux     {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_N-1NO->O_Ext-1N-R_Ext-3R-R",
    group = 
"""
1 *1 N   u0 r0 {2,S} {3,S} {5,S}
2 *2 R   u0 r0 {1,S}
3    R   u0 r0 {1,S} {6,[S,D,T,B,Q]}
4 *3 Li  u1 p0 c0 r0
5    C   u0 r0 {1,S}
6    R!H ux {3,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_N-1NO->O_Ext-1N-R_Ext-5R!H-R",
    group = 
"""
1 *1 N  u0 {2,S} {3,S} {5,S}
2 *2 R  u0 {1,S}
3    H  u0 {1,S}
4 *3 Li u1 p0 c0
5    C  u0 {1,S} {6,S}
6    C  u0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_N-1NO->O_Ext-1N-R_Ext-5R!H-R_2R->C",
    group = 
"""
1 *1 N  u0 r0 {2,S} {3,S} {5,S}
2 *2 C  u0 r0 {1,S}
3    H  u0 r0 {1,S}
4 *3 Li u1 p0 c0 r0
5    C  u0 r0 {1,S} {6,S}
6    C  u0 r0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_N-1NO->O_Ext-1N-R_Ext-5R!H-R_N-2R->C",
    group = 
"""
1 *1 N  u0 r0 {2,S} {3,S} {5,S}
2 *2 H  u0 r0 {1,S}
3    H  u0 r0 {1,S}
4 *3 Li u1 p0 c0 r0
5    C  u0 r0 {1,S} {6,S}
6    C  u0 r0 {5,S}
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_N-1NO->O_Ext-1N-R_3R->C",
    group = 
"""
1 *1 N  u0     {2,S} {3,S} {5,[S,D,T,B,Q]}
2 *2 R  u[0,1] {1,S}
3    C  u0     {1,S}
4 *3 Li u1     p0 c0
5    C  ux     {1,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_N-1NO->O_Ext-1N-R_N-3R->C",
    group = 
"""
1 *1 N  u0     {2,S} {3,S} {5,S}
2 *2 R  u[0,1] {1,S}
3    H  u0     {1,S}
4 *3 Li u1     p0 c0
5    C  u0     {1,S}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_N-1NO->O_Ext-1N-R_N-3R->C_2R->C",
    group = 
"""
1 *1 N  u0 r0 {2,S} {3,S} {5,S}
2 *2 C  u0 r0 {1,S}
3    H  u0 r0 {1,S}
4 *3 Li u1 p0 c0 r0
5    C  u0 r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_N-1NO->O_Ext-1N-R_N-3R->C_N-2R->C",
    group = 
"""
1 *1 N  u0     r0 {2,S} {3,S} {5,S}
2 *2 H  u[0,1] {1,S}
3    H  u0     {1,S}
4 *3 Li u1     p0 c0 r0
5    C  u0     r0 {1,S}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_N-1NO->O_2R->C",
    group = 
"""
1 *1 N  u0     {2,S} {3,S}
2 *2 C  u[0,1] {1,S}
3    H  u0     {1,S}
4 *3 Li u1     p0 c0
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_N-1NO->O_N-2R->C",
    group = 
"""
1 *1 N  u0     {2,S} {3,S}
2 *2 H  u[0,1] {1,S}
3    H  u0     {1,S}
4 *3 Li u1     p0 c0
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_1NO->O
        L3: Root_1NO->O_Ext-3R-R
            L4: Root_1NO->O_Ext-3R-R_2R->C
                L5: Root_1NO->O_Ext-3R-R_2R->C_Ext-5R!H-R
            L4: Root_1NO->O_Ext-3R-R_N-2R->C
        L3: Root_1NO->O_3R->C
            L4: Root_1NO->O_3R->C_Ext-2R-R
            L4: Root_1NO->O_3R->C_2R->C
            L4: Root_1NO->O_3R->C_N-2R->C
        L3: Root_1NO->O_N-3R->C
            L4: Root_1NO->O_N-3R->C_2R->C
                L5: Root_1NO->O_N-3R->C_2R->C_Ext-2C-R
            L4: Root_1NO->O_N-3R->C_N-2R->C
    L2: Root_N-1NO->O
        L3: Root_N-1NO->O_Ext-2R-R
            L4: Root_N-1NO->O_Ext-2R-R_Ext-1N-R
        L3: Root_N-1NO->O_Ext-1N-R
            L4: Root_N-1NO->O_Ext-1N-R_Ext-3R-R
            L4: Root_N-1NO->O_Ext-1N-R_Ext-5R!H-R
                L5: Root_N-1NO->O_Ext-1N-R_Ext-5R!H-R_2R->C
                L5: Root_N-1NO->O_Ext-1N-R_Ext-5R!H-R_N-2R->C
            L4: Root_N-1NO->O_Ext-1N-R_3R->C
            L4: Root_N-1NO->O_Ext-1N-R_N-3R->C
                L5: Root_N-1NO->O_Ext-1N-R_N-3R->C_2R->C
                L5: Root_N-1NO->O_Ext-1N-R_N-3R->C_N-2R->C
        L3: Root_N-1NO->O_2R->C
        L3: Root_N-1NO->O_N-2R->C
"""
)


forbidden(
    label = "Ar_metastable_biradical",
    group =
"""
1 *2 Ar u2 p3 c0
""",
    shortDesc = """Metastable argon is out of scope for this family.""",
    longDesc = """
METASTABLE ARGON, Ar(4s 3P2), IS OUT OF SCOPE HERE AND ITS PRODUCTS ARE NOT
REPRESENTABLE.
`Ar u2 p3 c0` is metastable argon, entered in
input/thermo/libraries/PlasmaExcitedNeutralThermo.py. It is a BIRADICAL, and the atom
type that perceives it, Ar0e, is declared generic under R/R!H in RMG-Py
(rmgpy/molecule/atomtype.py) -- correctly, which is the point of this entry. Argon
brings 8 valence electrons, so in a MOLECULE 8 - c = bonds + 2p + u (the 8 is argon's
valence count, not a universal constant), and a bond-free neutral argon at p3 c0 has u2 and no
choice about it: Ar0e perceives exactly one molecule, this one. A generic site at
u2 is RIGHT to match it. What is missing is this family's own statement of scope,
which is what this entry supplies. This family is for substitution at a lithium centre, which is not chemistry a
noble gas participates in.

HOW THIS FAMILY WAS FOUND, AND WHY IT IS NOT A SIXTH GUESS. Not by trying partners. The
shipped template space was decomposed and every family whose per-reactant site admits
`Ar u2 p3 c0` was selected -- see docs/argon-metastable-thermo/template_space_derivation.py,
which re-runs and exits non-zero if any matching family lacks this entry. This family
matches on the reverse template, slot 1. The earlier five entries were found by
running 140 families against a hardcoded partner list; that is exhaustive in families and
a SAMPLE in partners, and it missed this one because no suitable partner was in the list.

WHAT IT PREVENTS, MEASURED WITH A PARTNER DERIVED FROM THIS FAMILY'S OWN TEMPLATE
(docs/argon-metastable-thermo/template_witness_probe.py, so the witness does not depend on
anybody's choice of second reactant): the REVERSE direction, [Ar]NH2+ + Li <=> Ar* + LiNH2, whose [Ar]NH2+ is a bonded argon CATION with no thermo.

WHY THE LABEL IS LOAD-BEARING. ForbiddenStructures.is_molecule_forbidden honours atom
labels (rmgpy/data/base.py), so an UNLABELLED `1 Ar u2 p3 c0` group silently matches
nothing during generation -- the molecule's argon is labelled *2 by then and cannot
map to an unlabelled group atom. This label is not chosen, it is read out of the
matcher's own mapping for this family's template.

THIS IS THE FIX, AT THE LAYER THE ERROR IS ON. Not a workaround held open pending an
engine change: the argon atom types are correct as they stand (owner's ruling,
2026-09-21; measured in docs/argon-metastable-thermo/atomtype_u_determined_probe.py).
atomtype.py's note that Ar0e "answers for five (u, p, c) triples" describes GROUP
patterns, where ux can be hand-written and no valency check applies -- families generate
molecules.

NOT COMPLETE, THOUGH -- but complete against the template space as it ships today. A
family added later whose site admits this structure would reopen the crash, and would be
declaring a u2 site broader than the chemistry it intends: the same defect as this one, in
that family, and fixed the same way. It would not be an engine defect returning. The
derivation above is the check that catches it, and it is re-runnable by whoever adds the
family.
""",
)
